// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FeatureError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FeatureError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FeatureError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FeatureError {
  return FeatureError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum CorePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct GeoMessage: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GeoMessage? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return GeoMessage(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: GeoMessage, rhs: GeoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CorePigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && CorePigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GeoMessage")
    CorePigeonInternal.deepHash(value: latitude, hasher: &hasher)
    CorePigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "GeoMessage(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BoundsMessage: Hashable, CustomStringConvertible {
  var south: Double
  var west: Double
  var north: Double
  var east: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BoundsMessage? {
    let south = pigeonVar_list[0] as! Double
    let west = pigeonVar_list[1] as! Double
    let north = pigeonVar_list[2] as! Double
    let east = pigeonVar_list[3] as! Double

    return BoundsMessage(
      south: south,
      west: west,
      north: north,
      east: east
    )
  }
  func toList() -> [Any?] {
    return [
      south,
      west,
      north,
      east,
    ]
  }
  static func == (lhs: BoundsMessage, rhs: BoundsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CorePigeonInternal.deepEquals(lhs.south, rhs.south) && CorePigeonInternal.deepEquals(lhs.west, rhs.west) && CorePigeonInternal.deepEquals(lhs.north, rhs.north) && CorePigeonInternal.deepEquals(lhs.east, rhs.east)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BoundsMessage")
    CorePigeonInternal.deepHash(value: south, hasher: &hasher)
    CorePigeonInternal.deepHash(value: west, hasher: &hasher)
    CorePigeonInternal.deepHash(value: north, hasher: &hasher)
    CorePigeonInternal.deepHash(value: east, hasher: &hasher)
  }

  public var description: String {
    return "BoundsMessage(south: \(String(describing: south)), west: \(String(describing: west)), north: \(String(describing: north)), east: \(String(describing: east)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RegionMessage: Hashable, CustomStringConvertible {
  var id: Int64
  var name: String
  var collection: Bool
  var downloadedMask: Int64
  var downloadingMask: Int64
  var size: Int64
  var localSize: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegionMessage? {
    let id = pigeonVar_list[0] as! Int64
    let name = pigeonVar_list[1] as! String
    let collection = pigeonVar_list[2] as! Bool
    let downloadedMask = pigeonVar_list[3] as! Int64
    let downloadingMask = pigeonVar_list[4] as! Int64
    let size = pigeonVar_list[5] as! Int64
    let localSize = pigeonVar_list[6] as! Int64

    return RegionMessage(
      id: id,
      name: name,
      collection: collection,
      downloadedMask: downloadedMask,
      downloadingMask: downloadingMask,
      size: size,
      localSize: localSize
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      collection,
      downloadedMask,
      downloadingMask,
      size,
      localSize,
    ]
  }
  static func == (lhs: RegionMessage, rhs: RegionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CorePigeonInternal.deepEquals(lhs.id, rhs.id) && CorePigeonInternal.deepEquals(lhs.name, rhs.name) && CorePigeonInternal.deepEquals(lhs.collection, rhs.collection) && CorePigeonInternal.deepEquals(lhs.downloadedMask, rhs.downloadedMask) && CorePigeonInternal.deepEquals(lhs.downloadingMask, rhs.downloadingMask) && CorePigeonInternal.deepEquals(lhs.size, rhs.size) && CorePigeonInternal.deepEquals(lhs.localSize, rhs.localSize)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegionMessage")
    CorePigeonInternal.deepHash(value: id, hasher: &hasher)
    CorePigeonInternal.deepHash(value: name, hasher: &hasher)
    CorePigeonInternal.deepHash(value: collection, hasher: &hasher)
    CorePigeonInternal.deepHash(value: downloadedMask, hasher: &hasher)
    CorePigeonInternal.deepHash(value: downloadingMask, hasher: &hasher)
    CorePigeonInternal.deepHash(value: size, hasher: &hasher)
    CorePigeonInternal.deepHash(value: localSize, hasher: &hasher)
  }

  public var description: String {
    return "RegionMessage(id: \(String(describing: id)), name: \(String(describing: name)), collection: \(String(describing: collection)), downloadedMask: \(String(describing: downloadedMask)), downloadingMask: \(String(describing: downloadingMask)), size: \(String(describing: size)), localSize: \(String(describing: localSize)))"
  }
}

private class CorePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GeoMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return BoundsMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return RegionMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CorePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GeoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BoundsMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RegionMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CorePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CorePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CorePigeonCodecWriter(data: data)
  }
}

class CorePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CorePigeonCodec(readerWriter: CorePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CoreHostApi {
  func initialize(apiKey: String) throws
  func addAssetDataSet(asset: String, dataSet: Int64) throws
  func regions(parent: Int64?, refresh: Bool, completion: @escaping (Result<[RegionMessage], Error>) -> Void)
  func downloadRegion(id: Int64, mask: Int64) throws
  func cancelRegionDownload(id: Int64) throws
  func deleteRegion(id: Int64, mask: Int64) throws
  func downloadArea(requestId: Int64, bounds: BoundsMessage, mask: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelRequest(requestId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CoreHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CorePigeonCodec.shared }
  /// Sets up an instance of `CoreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CoreHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        do {
          try api.initialize(apiKey: apiKeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let addAssetDataSetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.addAssetDataSet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAssetDataSetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetArg = args[0] as! String
        let dataSetArg = args[1] as! Int64
        do {
          try api.addAssetDataSet(asset: assetArg, dataSet: dataSetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAssetDataSetChannel.setMessageHandler(nil)
    }
    let regionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.regions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      regionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parentArg: Int64? = nilOrValue(args[0])
        let refreshArg = args[1] as! Bool
        api.regions(parent: parentArg, refresh: refreshArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      regionsChannel.setMessageHandler(nil)
    }
    let downloadRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.downloadRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let maskArg = args[1] as! Int64
        do {
          try api.downloadRegion(id: idArg, mask: maskArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      downloadRegionChannel.setMessageHandler(nil)
    }
    let cancelRegionDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.cancelRegionDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRegionDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.cancelRegionDownload(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRegionDownloadChannel.setMessageHandler(nil)
    }
    let deleteRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.deleteRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let maskArg = args[1] as! Int64
        do {
          try api.deleteRegion(id: idArg, mask: maskArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteRegionChannel.setMessageHandler(nil)
    }
    let downloadAreaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.downloadArea\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadAreaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let boundsArg = args[1] as! BoundsMessage
        let maskArg = args[2] as! Int64
        api.downloadArea(requestId: requestIdArg, bounds: boundsArg, mask: maskArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadAreaChannel.setMessageHandler(nil)
    }
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_core.CoreHostApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SdkEventsApiProtocol {
  @MainActor func downloadProgress(id idArg: Int64, dataSet dataSetArg: Int64, downloaded downloadedArg: Int64, total totalArg: Int64, error errorArg: String?, finished finishedArg: Bool, area areaArg: Bool) async throws
}
class SdkEventsApi: SdkEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CorePigeonCodec {
    return CorePigeonCodec.shared
  }
  @MainActor func downloadProgress(id idArg: Int64, dataSet dataSetArg: Int64, downloaded downloadedArg: Int64, total totalArg: Int64, error errorArg: String?, finished finishedArg: Bool, area areaArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.glmap_core.SdkEventsApi.downloadProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([idArg, dataSetArg, downloadedArg, totalArg, errorArg, finishedArg, areaArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FeatureError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
