name: globus_flutter_workspace
publish_to: none
environment:
  sdk: ^3.13.3
workspace:
  - packages/glmap_core
  - packages/glmap
  - packages/glsearch
  - packages/glroute
  - example
dev_dependencies:
  pigeon: 29.0.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
