// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package software.globus.lab.glmap_lab

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object FeaturesPigeonUtils {

  fun createConnectionError(channelName: String): FeatureError {
    return FeatureError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FeatureError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FeatureError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class GeoMessage (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GeoMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return GeoMessage(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GeoMessage
    return FeaturesPigeonUtils.deepEquals(this.latitude, other.latitude) && FeaturesPigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "GeoMessage(latitude=$latitude, longitude=$longitude)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BoundsMessage (
  val south: Double,
  val west: Double,
  val north: Double,
  val east: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BoundsMessage {
      val south = pigeonVar_list[0] as Double
      val west = pigeonVar_list[1] as Double
      val north = pigeonVar_list[2] as Double
      val east = pigeonVar_list[3] as Double
      return BoundsMessage(south, west, north, east)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      south,
      west,
      north,
      east,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BoundsMessage
    return FeaturesPigeonUtils.deepEquals(this.south, other.south) && FeaturesPigeonUtils.deepEquals(this.west, other.west) && FeaturesPigeonUtils.deepEquals(this.north, other.north) && FeaturesPigeonUtils.deepEquals(this.east, other.east)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.south)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.west)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.north)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.east)
    return result
  }
  override fun toString(): String {
    return "BoundsMessage(south=$south, west=$west, north=$north, east=$east)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaceMessage (
  val name: String,
  val detail: String,
  val point: GeoMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaceMessage {
      val name = pigeonVar_list[0] as String
      val detail = pigeonVar_list[1] as String
      val point = pigeonVar_list[2] as GeoMessage
      return PlaceMessage(name, detail, point)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      detail,
      point,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaceMessage
    return FeaturesPigeonUtils.deepEquals(this.name, other.name) && FeaturesPigeonUtils.deepEquals(this.detail, other.detail) && FeaturesPigeonUtils.deepEquals(this.point, other.point)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.name)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.detail)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.point)
    return result
  }
  override fun toString(): String {
    return "PlaceMessage(name=$name, detail=$detail, point=$point)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RouteMessage (
  val id: Long,
  val distance: Double,
  val duration: Double,
  val bounds: BoundsMessage,
  val lonLat: DoubleArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteMessage {
      val id = pigeonVar_list[0] as Long
      val distance = pigeonVar_list[1] as Double
      val duration = pigeonVar_list[2] as Double
      val bounds = pigeonVar_list[3] as BoundsMessage
      val lonLat = pigeonVar_list[4] as DoubleArray
      return RouteMessage(id, distance, duration, bounds, lonLat)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      distance,
      duration,
      bounds,
      lonLat,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RouteMessage
    return FeaturesPigeonUtils.deepEquals(this.id, other.id) && FeaturesPigeonUtils.deepEquals(this.distance, other.distance) && FeaturesPigeonUtils.deepEquals(this.duration, other.duration) && FeaturesPigeonUtils.deepEquals(this.bounds, other.bounds) && FeaturesPigeonUtils.deepEquals(this.lonLat, other.lonLat)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.id)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.distance)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.duration)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.bounds)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.lonLat)
    return result
  }
  override fun toString(): String {
    return "RouteMessage(id=$id, distance=$distance, duration=$duration, bounds=$bounds, lonLat=${lonLat.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NavigationMessage (
  val instruction: String,
  val distanceToManeuver: Double,
  val remainingDistance: Double,
  val remainingDuration: Double,
  val progress: Double,
  val onRoute: Boolean,
  val point: GeoMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavigationMessage {
      val instruction = pigeonVar_list[0] as String
      val distanceToManeuver = pigeonVar_list[1] as Double
      val remainingDistance = pigeonVar_list[2] as Double
      val remainingDuration = pigeonVar_list[3] as Double
      val progress = pigeonVar_list[4] as Double
      val onRoute = pigeonVar_list[5] as Boolean
      val point = pigeonVar_list[6] as GeoMessage
      return NavigationMessage(instruction, distanceToManeuver, remainingDistance, remainingDuration, progress, onRoute, point)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      instruction,
      distanceToManeuver,
      remainingDistance,
      remainingDuration,
      progress,
      onRoute,
      point,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NavigationMessage
    return FeaturesPigeonUtils.deepEquals(this.instruction, other.instruction) && FeaturesPigeonUtils.deepEquals(this.distanceToManeuver, other.distanceToManeuver) && FeaturesPigeonUtils.deepEquals(this.remainingDistance, other.remainingDistance) && FeaturesPigeonUtils.deepEquals(this.remainingDuration, other.remainingDuration) && FeaturesPigeonUtils.deepEquals(this.progress, other.progress) && FeaturesPigeonUtils.deepEquals(this.onRoute, other.onRoute) && FeaturesPigeonUtils.deepEquals(this.point, other.point)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.instruction)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.distanceToManeuver)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.remainingDistance)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.remainingDuration)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.progress)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.onRoute)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.point)
    return result
  }
  override fun toString(): String {
    return "NavigationMessage(instruction=$instruction, distanceToManeuver=$distanceToManeuver, remainingDistance=$remainingDistance, remainingDuration=$remainingDuration, progress=$progress, onRoute=$onRoute, point=$point)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RegionMessage (
  val id: Long,
  val name: String,
  val collection: Boolean,
  val downloadedMask: Long,
  val downloadingMask: Long,
  val size: Long,
  val localSize: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegionMessage {
      val id = pigeonVar_list[0] as Long
      val name = pigeonVar_list[1] as String
      val collection = pigeonVar_list[2] as Boolean
      val downloadedMask = pigeonVar_list[3] as Long
      val downloadingMask = pigeonVar_list[4] as Long
      val size = pigeonVar_list[5] as Long
      val localSize = pigeonVar_list[6] as Long
      return RegionMessage(id, name, collection, downloadedMask, downloadingMask, size, localSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      collection,
      downloadedMask,
      downloadingMask,
      size,
      localSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegionMessage
    return FeaturesPigeonUtils.deepEquals(this.id, other.id) && FeaturesPigeonUtils.deepEquals(this.name, other.name) && FeaturesPigeonUtils.deepEquals(this.collection, other.collection) && FeaturesPigeonUtils.deepEquals(this.downloadedMask, other.downloadedMask) && FeaturesPigeonUtils.deepEquals(this.downloadingMask, other.downloadingMask) && FeaturesPigeonUtils.deepEquals(this.size, other.size) && FeaturesPigeonUtils.deepEquals(this.localSize, other.localSize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.id)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.name)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.collection)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.downloadedMask)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.downloadingMask)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.size)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.localSize)
    return result
  }
  override fun toString(): String {
    return "RegionMessage(id=$id, name=$name, collection=$collection, downloadedMask=$downloadedMask, downloadingMask=$downloadingMask, size=$size, localSize=$localSize)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RouteStepMessage (
  val lonLat: DoubleArray,
  val instruction: String,
  val turn: Long,
  val duration: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteStepMessage {
      val lonLat = pigeonVar_list[0] as DoubleArray
      val instruction = pigeonVar_list[1] as String
      val turn = pigeonVar_list[2] as Long
      val duration = pigeonVar_list[3] as Double
      return RouteStepMessage(lonLat, instruction, turn, duration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lonLat,
      instruction,
      turn,
      duration,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RouteStepMessage
    return FeaturesPigeonUtils.deepEquals(this.lonLat, other.lonLat) && FeaturesPigeonUtils.deepEquals(this.instruction, other.instruction) && FeaturesPigeonUtils.deepEquals(this.turn, other.turn) && FeaturesPigeonUtils.deepEquals(this.duration, other.duration)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.lonLat)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.instruction)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.turn)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.duration)
    return result
  }
  override fun toString(): String {
    return "RouteStepMessage(lonLat=${lonLat.contentToString()}, instruction=$instruction, turn=$turn, duration=$duration)"
  }
}
private open class FeaturesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GeoMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BoundsMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaceMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NavigationMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegionMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteStepMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GeoMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BoundsMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PlaceMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RouteMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NavigationMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is RegionMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RouteStepMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SdkHostApi {
  fun initialize(apiKey: String)
  fun addAssetDataSet(asset: String, dataSet: Long)
  fun regions(parent: Long?, refresh: Boolean, callback: (Result<List<RegionMessage>>) -> Unit)
  fun downloadRegion(id: Long, mask: Long)
  fun cancelRegionDownload(id: Long)
  fun deleteRegion(id: Long, mask: Long)
  fun downloadArea(requestId: Long, bounds: BoundsMessage, mask: Long, callback: (Result<Unit>) -> Unit)
  fun search(requestId: Long, text: String, offline: Boolean, autocomplete: Boolean, center: GeoMessage, categories: List<String>, callback: (Result<List<PlaceMessage>>) -> Unit)
  fun route(requestId: Long, start: GeoMessage, end: GeoMessage, mode: String, offline: Boolean, offlineConfig: String?, callback: (Result<RouteMessage>) -> Unit)
  fun cancelRequest(requestId: Long)
  fun updateNavigation(routeId: Long, point: GeoMessage, bearing: Double): NavigationMessage
  fun releaseRoute(routeId: Long)
  fun buildRoute(steps: List<RouteStepMessage>): RouteMessage

  companion object {
    /** The codec used by SdkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FeaturesPigeonCodec()
    }
    /** Sets up an instance of `SdkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SdkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.initialize(apiKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.addAssetDataSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetArg = args[0] as String
            val dataSetArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.addAssetDataSet(assetArg, dataSetArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.regions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parentArg = args[0] as Long?
            val refreshArg = args[1] as Boolean
            api.regions(parentArg, refreshArg) { result: Result<List<RegionMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FeaturesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.downloadRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val maskArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.downloadRegion(idArg, maskArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.cancelRegionDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRegionDownload(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.deleteRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val maskArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.deleteRegion(idArg, maskArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.downloadArea$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val boundsArg = args[1] as BoundsMessage
            val maskArg = args[2] as Long
            api.downloadArea(requestIdArg, boundsArg, maskArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                reply.reply(FeaturesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.search$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val textArg = args[1] as String
            val offlineArg = args[2] as Boolean
            val autocompleteArg = args[3] as Boolean
            val centerArg = args[4] as GeoMessage
            val categoriesArg = args[5] as List<String>
            api.search(requestIdArg, textArg, offlineArg, autocompleteArg, centerArg, categoriesArg) { result: Result<List<PlaceMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FeaturesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.route$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val startArg = args[1] as GeoMessage
            val endArg = args[2] as GeoMessage
            val modeArg = args[3] as String
            val offlineArg = args[4] as Boolean
            val offlineConfigArg = args[5] as String?
            api.route(requestIdArg, startArg, endArg, modeArg, offlineArg, offlineConfigArg) { result: Result<RouteMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FeaturesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRequest(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.updateNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeIdArg = args[0] as Long
            val pointArg = args[1] as GeoMessage
            val bearingArg = args[2] as Double
            val wrapped: List<Any?> = try {
              listOf(api.updateNavigation(routeIdArg, pointArg, bearingArg))
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.releaseRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.releaseRoute(routeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.SdkHostApi.buildRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stepsArg = args[0] as List<RouteStepMessage>
            val wrapped: List<Any?> = try {
              listOf(api.buildRoute(stepsArg))
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SdkEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SdkEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      FeaturesPigeonCodec()
    }
  }
  suspend fun downloadProgress(idArg: Long, dataSetArg: Long, downloadedArg: Long, totalArg: Long, errorArg: String?, finishedArg: Boolean, areaArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.glmap_lab.SdkEventsApi.downloadProgress$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(idArg, dataSetArg, downloadedArg, totalArg, errorArg, finishedArg, areaArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FeatureError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(FeaturesPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MapFeaturesHostApi {
  fun setStyleOptions(options: Map<String, String>, assetDirectory: String?)
  fun setTerrain(altitudeScale: Double, hillshades: Boolean, contours: Boolean, slopes: Boolean)
  fun setOnlineTiles(enabled: Boolean)
  fun setRasterSource(urlTemplate: String?, attribution: String)
  fun animateCamera(center: GeoMessage, zoom: Double, duration: Double, fly: Boolean)
  fun fitBounds(bounds: BoundsMessage)
  fun setImage(id: Long, point: GeoMessage, png: ByteArray)
  fun setImageGroup(id: Long, points: List<GeoMessage>, png: ByteArray)
  fun setMarkers(id: Long, geoJson: String, png: ByteArray, clusteringRadius: Double)
  fun setBalloon(id: Long, point: GeoMessage, text: String)
  fun setTrack(id: Long, lonLat: DoubleArray, progress: Double, arrows: Boolean)
  fun setRouteTrack(id: Long, routeId: Long, progress: Double)
  fun removeObject(id: Long)
  fun pickObject(x: Double, y: Double, callback: (Result<PlaceMessage?>) -> Unit)
  fun project(points: List<GeoMessage>, callback: (Result<DoubleArray>) -> Unit)

  companion object {
    /** The codec used by MapFeaturesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FeaturesPigeonCodec()
    }
    /** Sets up an instance of `MapFeaturesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MapFeaturesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setStyleOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as Map<String, String>
            val assetDirectoryArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.setStyleOptions(optionsArg, assetDirectoryArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setTerrain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val altitudeScaleArg = args[0] as Double
            val hillshadesArg = args[1] as Boolean
            val contoursArg = args[2] as Boolean
            val slopesArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.setTerrain(altitudeScaleArg, hillshadesArg, contoursArg, slopesArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setOnlineTiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setOnlineTiles(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setRasterSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlTemplateArg = args[0] as String?
            val attributionArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.setRasterSource(urlTemplateArg, attributionArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.animateCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val centerArg = args[0] as GeoMessage
            val zoomArg = args[1] as Double
            val durationArg = args[2] as Double
            val flyArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.animateCamera(centerArg, zoomArg, durationArg, flyArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.fitBounds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val boundsArg = args[0] as BoundsMessage
            val wrapped: List<Any?> = try {
              api.fitBounds(boundsArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val pointArg = args[1] as GeoMessage
            val pngArg = args[2] as ByteArray
            val wrapped: List<Any?> = try {
              api.setImage(idArg, pointArg, pngArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setImageGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val pointsArg = args[1] as List<GeoMessage>
            val pngArg = args[2] as ByteArray
            val wrapped: List<Any?> = try {
              api.setImageGroup(idArg, pointsArg, pngArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setMarkers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val geoJsonArg = args[1] as String
            val pngArg = args[2] as ByteArray
            val clusteringRadiusArg = args[3] as Double
            val wrapped: List<Any?> = try {
              api.setMarkers(idArg, geoJsonArg, pngArg, clusteringRadiusArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setBalloon$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val pointArg = args[1] as GeoMessage
            val textArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.setBalloon(idArg, pointArg, textArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val lonLatArg = args[1] as DoubleArray
            val progressArg = args[2] as Double
            val arrowsArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.setTrack(idArg, lonLatArg, progressArg, arrowsArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setRouteTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val routeIdArg = args[1] as Long
            val progressArg = args[2] as Double
            val wrapped: List<Any?> = try {
              api.setRouteTrack(idArg, routeIdArg, progressArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.removeObject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.removeObject(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.pickObject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val xArg = args[0] as Double
            val yArg = args[1] as Double
            api.pickObject(xArg, yArg) { result: Result<PlaceMessage?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FeaturesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.project$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pointsArg = args[0] as List<GeoMessage>
            api.project(pointsArg) { result: Result<DoubleArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FeaturesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MapEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MapEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      FeaturesPigeonCodec()
    }
  }
  suspend fun tap(pointArg: GeoMessage, xArg: Double, yArg: Double, longPressArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.glmap_lab.MapEventsApi.tap$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pointArg, xArg, yArg, longPressArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FeatureError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(FeaturesPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
}
