// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package software.globus.flutter.glroute

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RoutePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FeatureError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FeatureError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class GeoMessage (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GeoMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return GeoMessage(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GeoMessage
    return RoutePigeonUtils.deepEquals(this.latitude, other.latitude) && RoutePigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RoutePigeonUtils.deepHash(this.latitude)
    result = 31 * result + RoutePigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "GeoMessage(latitude=$latitude, longitude=$longitude)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BoundsMessage (
  val south: Double,
  val west: Double,
  val north: Double,
  val east: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BoundsMessage {
      val south = pigeonVar_list[0] as Double
      val west = pigeonVar_list[1] as Double
      val north = pigeonVar_list[2] as Double
      val east = pigeonVar_list[3] as Double
      return BoundsMessage(south, west, north, east)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      south,
      west,
      north,
      east,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BoundsMessage
    return RoutePigeonUtils.deepEquals(this.south, other.south) && RoutePigeonUtils.deepEquals(this.west, other.west) && RoutePigeonUtils.deepEquals(this.north, other.north) && RoutePigeonUtils.deepEquals(this.east, other.east)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RoutePigeonUtils.deepHash(this.south)
    result = 31 * result + RoutePigeonUtils.deepHash(this.west)
    result = 31 * result + RoutePigeonUtils.deepHash(this.north)
    result = 31 * result + RoutePigeonUtils.deepHash(this.east)
    return result
  }
  override fun toString(): String {
    return "BoundsMessage(south=$south, west=$west, north=$north, east=$east)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RouteMessage (
  val id: Long,
  val distance: Double,
  val duration: Double,
  val bounds: BoundsMessage,
  val lonLat: DoubleArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteMessage {
      val id = pigeonVar_list[0] as Long
      val distance = pigeonVar_list[1] as Double
      val duration = pigeonVar_list[2] as Double
      val bounds = pigeonVar_list[3] as BoundsMessage
      val lonLat = pigeonVar_list[4] as DoubleArray
      return RouteMessage(id, distance, duration, bounds, lonLat)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      distance,
      duration,
      bounds,
      lonLat,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RouteMessage
    return RoutePigeonUtils.deepEquals(this.id, other.id) && RoutePigeonUtils.deepEquals(this.distance, other.distance) && RoutePigeonUtils.deepEquals(this.duration, other.duration) && RoutePigeonUtils.deepEquals(this.bounds, other.bounds) && RoutePigeonUtils.deepEquals(this.lonLat, other.lonLat)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RoutePigeonUtils.deepHash(this.id)
    result = 31 * result + RoutePigeonUtils.deepHash(this.distance)
    result = 31 * result + RoutePigeonUtils.deepHash(this.duration)
    result = 31 * result + RoutePigeonUtils.deepHash(this.bounds)
    result = 31 * result + RoutePigeonUtils.deepHash(this.lonLat)
    return result
  }
  override fun toString(): String {
    return "RouteMessage(id=$id, distance=$distance, duration=$duration, bounds=$bounds, lonLat=${lonLat.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NavigationMessage (
  val instruction: String,
  val distanceToManeuver: Double,
  val remainingDistance: Double,
  val remainingDuration: Double,
  val progress: Double,
  val onRoute: Boolean,
  val point: GeoMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavigationMessage {
      val instruction = pigeonVar_list[0] as String
      val distanceToManeuver = pigeonVar_list[1] as Double
      val remainingDistance = pigeonVar_list[2] as Double
      val remainingDuration = pigeonVar_list[3] as Double
      val progress = pigeonVar_list[4] as Double
      val onRoute = pigeonVar_list[5] as Boolean
      val point = pigeonVar_list[6] as GeoMessage
      return NavigationMessage(instruction, distanceToManeuver, remainingDistance, remainingDuration, progress, onRoute, point)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      instruction,
      distanceToManeuver,
      remainingDistance,
      remainingDuration,
      progress,
      onRoute,
      point,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NavigationMessage
    return RoutePigeonUtils.deepEquals(this.instruction, other.instruction) && RoutePigeonUtils.deepEquals(this.distanceToManeuver, other.distanceToManeuver) && RoutePigeonUtils.deepEquals(this.remainingDistance, other.remainingDistance) && RoutePigeonUtils.deepEquals(this.remainingDuration, other.remainingDuration) && RoutePigeonUtils.deepEquals(this.progress, other.progress) && RoutePigeonUtils.deepEquals(this.onRoute, other.onRoute) && RoutePigeonUtils.deepEquals(this.point, other.point)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RoutePigeonUtils.deepHash(this.instruction)
    result = 31 * result + RoutePigeonUtils.deepHash(this.distanceToManeuver)
    result = 31 * result + RoutePigeonUtils.deepHash(this.remainingDistance)
    result = 31 * result + RoutePigeonUtils.deepHash(this.remainingDuration)
    result = 31 * result + RoutePigeonUtils.deepHash(this.progress)
    result = 31 * result + RoutePigeonUtils.deepHash(this.onRoute)
    result = 31 * result + RoutePigeonUtils.deepHash(this.point)
    return result
  }
  override fun toString(): String {
    return "NavigationMessage(instruction=$instruction, distanceToManeuver=$distanceToManeuver, remainingDistance=$remainingDistance, remainingDuration=$remainingDuration, progress=$progress, onRoute=$onRoute, point=$point)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RouteStepMessage (
  val lonLat: DoubleArray,
  val instruction: String,
  val turn: Long,
  val duration: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteStepMessage {
      val lonLat = pigeonVar_list[0] as DoubleArray
      val instruction = pigeonVar_list[1] as String
      val turn = pigeonVar_list[2] as Long
      val duration = pigeonVar_list[3] as Double
      return RouteStepMessage(lonLat, instruction, turn, duration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lonLat,
      instruction,
      turn,
      duration,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RouteStepMessage
    return RoutePigeonUtils.deepEquals(this.lonLat, other.lonLat) && RoutePigeonUtils.deepEquals(this.instruction, other.instruction) && RoutePigeonUtils.deepEquals(this.turn, other.turn) && RoutePigeonUtils.deepEquals(this.duration, other.duration)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RoutePigeonUtils.deepHash(this.lonLat)
    result = 31 * result + RoutePigeonUtils.deepHash(this.instruction)
    result = 31 * result + RoutePigeonUtils.deepHash(this.turn)
    result = 31 * result + RoutePigeonUtils.deepHash(this.duration)
    return result
  }
  override fun toString(): String {
    return "RouteStepMessage(lonLat=${lonLat.contentToString()}, instruction=$instruction, turn=$turn, duration=$duration)"
  }
}
private open class RoutePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GeoMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BoundsMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NavigationMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteStepMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GeoMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BoundsMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is RouteMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NavigationMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is RouteStepMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RouteHostApi {
  fun route(requestId: Long, start: GeoMessage, end: GeoMessage, mode: String, offline: Boolean, offlineConfig: String?, callback: (Result<RouteMessage>) -> Unit)
  fun cancelRequest(requestId: Long)
  fun updateNavigation(routeId: Long, point: GeoMessage, bearing: Double): NavigationMessage
  fun releaseRoute(routeId: Long)
  fun buildRoute(steps: List<RouteStepMessage>): RouteMessage

  companion object {
    /** The codec used by RouteHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      RoutePigeonCodec()
    }
    /** Sets up an instance of `RouteHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RouteHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glroute.RouteHostApi.route$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val startArg = args[1] as GeoMessage
            val endArg = args[2] as GeoMessage
            val modeArg = args[3] as String
            val offlineArg = args[4] as Boolean
            val offlineConfigArg = args[5] as String?
            api.route(requestIdArg, startArg, endArg, modeArg, offlineArg, offlineConfigArg) { result: Result<RouteMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(RoutePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(RoutePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glroute.RouteHostApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRequest(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RoutePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glroute.RouteHostApi.updateNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeIdArg = args[0] as Long
            val pointArg = args[1] as GeoMessage
            val bearingArg = args[2] as Double
            val wrapped: List<Any?> = try {
              listOf(api.updateNavigation(routeIdArg, pointArg, bearingArg))
            } catch (exception: Throwable) {
              RoutePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glroute.RouteHostApi.releaseRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.releaseRoute(routeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RoutePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glroute.RouteHostApi.buildRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val stepsArg = args[0] as List<RouteStepMessage>
            val wrapped: List<Any?> = try {
              listOf(api.buildRoute(stepsArg))
            } catch (exception: Throwable) {
              RoutePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
