// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package software.globus.flutter.glmap

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object FeaturesPigeonUtils {

  fun createConnectionError(channelName: String): FeatureError {
    return FeatureError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FeatureError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FeatureError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class GeoMessage (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GeoMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return GeoMessage(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GeoMessage
    return FeaturesPigeonUtils.deepEquals(this.latitude, other.latitude) && FeaturesPigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "GeoMessage(latitude=$latitude, longitude=$longitude)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BoundsMessage (
  val south: Double,
  val west: Double,
  val north: Double,
  val east: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BoundsMessage {
      val south = pigeonVar_list[0] as Double
      val west = pigeonVar_list[1] as Double
      val north = pigeonVar_list[2] as Double
      val east = pigeonVar_list[3] as Double
      return BoundsMessage(south, west, north, east)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      south,
      west,
      north,
      east,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BoundsMessage
    return FeaturesPigeonUtils.deepEquals(this.south, other.south) && FeaturesPigeonUtils.deepEquals(this.west, other.west) && FeaturesPigeonUtils.deepEquals(this.north, other.north) && FeaturesPigeonUtils.deepEquals(this.east, other.east)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.south)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.west)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.north)
    result = 31 * result + FeaturesPigeonUtils.deepHash(this.east)
    return result
  }
  override fun toString(): String {
    return "BoundsMessage(south=$south, west=$west, north=$north, east=$east)"
  }
}
private open class FeaturesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GeoMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BoundsMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GeoMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BoundsMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MapFeaturesHostApi {
  fun setStyleOptions(options: Map<String, String>, assetDirectory: String?)
  fun setTerrain(altitudeScale: Double, hillshades: Boolean, contours: Boolean, slopes: Boolean)
  fun setOnlineTiles(enabled: Boolean)
  fun setRasterSource(urlTemplate: String?, attribution: String)
  fun animateCamera(center: GeoMessage, zoom: Double, duration: Double, fly: Boolean)
  fun fitBounds(bounds: BoundsMessage)
  fun setImage(id: Long, point: GeoMessage, png: ByteArray)
  fun setImageGroup(id: Long, points: List<GeoMessage>, png: ByteArray)
  fun setMarkers(id: Long, geoJson: String, png: ByteArray, clusteringRadius: Double)
  fun setBalloon(id: Long, point: GeoMessage, text: String)
  fun setTrack(id: Long, lonLat: DoubleArray, progress: Double, arrows: Boolean)
  fun setRouteTrack(id: Long, routeId: Long, progress: Double)
  fun removeObject(id: Long)
  fun project(points: List<GeoMessage>, callback: (Result<DoubleArray>) -> Unit)

  companion object {
    /** The codec used by MapFeaturesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FeaturesPigeonCodec()
    }
    /** Sets up an instance of `MapFeaturesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MapFeaturesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setStyleOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as Map<String, String>
            val assetDirectoryArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.setStyleOptions(optionsArg, assetDirectoryArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setTerrain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val altitudeScaleArg = args[0] as Double
            val hillshadesArg = args[1] as Boolean
            val contoursArg = args[2] as Boolean
            val slopesArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.setTerrain(altitudeScaleArg, hillshadesArg, contoursArg, slopesArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setOnlineTiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setOnlineTiles(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setRasterSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlTemplateArg = args[0] as String?
            val attributionArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.setRasterSource(urlTemplateArg, attributionArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.animateCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val centerArg = args[0] as GeoMessage
            val zoomArg = args[1] as Double
            val durationArg = args[2] as Double
            val flyArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.animateCamera(centerArg, zoomArg, durationArg, flyArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.fitBounds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val boundsArg = args[0] as BoundsMessage
            val wrapped: List<Any?> = try {
              api.fitBounds(boundsArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val pointArg = args[1] as GeoMessage
            val pngArg = args[2] as ByteArray
            val wrapped: List<Any?> = try {
              api.setImage(idArg, pointArg, pngArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setImageGroup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val pointsArg = args[1] as List<GeoMessage>
            val pngArg = args[2] as ByteArray
            val wrapped: List<Any?> = try {
              api.setImageGroup(idArg, pointsArg, pngArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setMarkers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val geoJsonArg = args[1] as String
            val pngArg = args[2] as ByteArray
            val clusteringRadiusArg = args[3] as Double
            val wrapped: List<Any?> = try {
              api.setMarkers(idArg, geoJsonArg, pngArg, clusteringRadiusArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setBalloon$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val pointArg = args[1] as GeoMessage
            val textArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.setBalloon(idArg, pointArg, textArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val lonLatArg = args[1] as DoubleArray
            val progressArg = args[2] as Double
            val arrowsArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.setTrack(idArg, lonLatArg, progressArg, arrowsArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.setRouteTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val routeIdArg = args[1] as Long
            val progressArg = args[2] as Double
            val wrapped: List<Any?> = try {
              api.setRouteTrack(idArg, routeIdArg, progressArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.removeObject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.removeObject(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              FeaturesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapFeaturesHostApi.project$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pointsArg = args[0] as List<GeoMessage>
            api.project(pointsArg) { result: Result<DoubleArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FeaturesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FeaturesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MapEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MapEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      FeaturesPigeonCodec()
    }
  }
  suspend fun tap(pointArg: GeoMessage, xArg: Double, yArg: Double, longPressArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.glmap.MapEventsApi.tap$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pointArg, xArg, yArg, longPressArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FeatureError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(FeaturesPigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
}
