// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package software.globus.flutter.glmap

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MapPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is MapApiError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class MapApiError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class VectorMutation(val raw: Int) {
  REPLACE(0),
  STYLE(1),
  REMOVE(2);

  companion object {
    fun ofRaw(raw: Int): VectorMutation? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VectorReply(val raw: Int) {
  READY(0),
  SUPERSEDED(1),
  CANCELLED(2),
  FAILED(3),
  REMOVED(4);

  companion object {
    fun ofRaw(raw: Int): VectorReply? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MapStateMessage (
  val latitude: Double,
  val longitude: Double,
  val zoom: Double,
  val scale: Double,
  val angle: Double,
  val pitch: Double,
  val originX: Double,
  val originY: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MapStateMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val zoom = pigeonVar_list[2] as Double
      val scale = pigeonVar_list[3] as Double
      val angle = pigeonVar_list[4] as Double
      val pitch = pigeonVar_list[5] as Double
      val originX = pigeonVar_list[6] as Double
      val originY = pigeonVar_list[7] as Double
      return MapStateMessage(latitude, longitude, zoom, scale, angle, pitch, originX, originY)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      zoom,
      scale,
      angle,
      pitch,
      originX,
      originY,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MapStateMessage
    return MapPigeonUtils.deepEquals(this.latitude, other.latitude) && MapPigeonUtils.deepEquals(this.longitude, other.longitude) && MapPigeonUtils.deepEquals(this.zoom, other.zoom) && MapPigeonUtils.deepEquals(this.scale, other.scale) && MapPigeonUtils.deepEquals(this.angle, other.angle) && MapPigeonUtils.deepEquals(this.pitch, other.pitch) && MapPigeonUtils.deepEquals(this.originX, other.originX) && MapPigeonUtils.deepEquals(this.originY, other.originY)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MapPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MapPigeonUtils.deepHash(this.longitude)
    result = 31 * result + MapPigeonUtils.deepHash(this.zoom)
    result = 31 * result + MapPigeonUtils.deepHash(this.scale)
    result = 31 * result + MapPigeonUtils.deepHash(this.angle)
    result = 31 * result + MapPigeonUtils.deepHash(this.pitch)
    result = 31 * result + MapPigeonUtils.deepHash(this.originX)
    result = 31 * result + MapPigeonUtils.deepHash(this.originY)
    return result
  }
  override fun toString(): String {
    return "MapStateMessage(latitude=$latitude, longitude=$longitude, zoom=$zoom, scale=$scale, angle=$angle, pitch=$pitch, originX=$originX, originY=$originY)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MapCameraMessage (
  val latitude: Double,
  val longitude: Double,
  val zoom: Double,
  val angle: Double,
  val pitch: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MapCameraMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val zoom = pigeonVar_list[2] as Double
      val angle = pigeonVar_list[3] as Double
      val pitch = pigeonVar_list[4] as Double
      return MapCameraMessage(latitude, longitude, zoom, angle, pitch)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      zoom,
      angle,
      pitch,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MapCameraMessage
    return MapPigeonUtils.deepEquals(this.latitude, other.latitude) && MapPigeonUtils.deepEquals(this.longitude, other.longitude) && MapPigeonUtils.deepEquals(this.zoom, other.zoom) && MapPigeonUtils.deepEquals(this.angle, other.angle) && MapPigeonUtils.deepEquals(this.pitch, other.pitch)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MapPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MapPigeonUtils.deepHash(this.longitude)
    result = 31 * result + MapPigeonUtils.deepHash(this.zoom)
    result = 31 * result + MapPigeonUtils.deepHash(this.angle)
    result = 31 * result + MapPigeonUtils.deepHash(this.pitch)
    return result
  }
  override fun toString(): String {
    return "MapCameraMessage(latitude=$latitude, longitude=$longitude, zoom=$zoom, angle=$angle, pitch=$pitch)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VectorMutationMessage (
  val layerId: Long,
  val operation: VectorMutation,
  val lonLat: DoubleArray? = null,
  val geoJson: String? = null,
  val style: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VectorMutationMessage {
      val layerId = pigeonVar_list[0] as Long
      val operation = pigeonVar_list[1] as VectorMutation
      val lonLat = pigeonVar_list[2] as DoubleArray?
      val geoJson = pigeonVar_list[3] as String?
      val style = pigeonVar_list[4] as String?
      return VectorMutationMessage(layerId, operation, lonLat, geoJson, style)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      layerId,
      operation,
      lonLat,
      geoJson,
      style,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VectorMutationMessage
    return MapPigeonUtils.deepEquals(this.layerId, other.layerId) && MapPigeonUtils.deepEquals(this.operation, other.operation) && MapPigeonUtils.deepEquals(this.lonLat, other.lonLat) && MapPigeonUtils.deepEquals(this.geoJson, other.geoJson) && MapPigeonUtils.deepEquals(this.style, other.style)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MapPigeonUtils.deepHash(this.layerId)
    result = 31 * result + MapPigeonUtils.deepHash(this.operation)
    result = 31 * result + MapPigeonUtils.deepHash(this.lonLat)
    result = 31 * result + MapPigeonUtils.deepHash(this.geoJson)
    result = 31 * result + MapPigeonUtils.deepHash(this.style)
    return result
  }
  override fun toString(): String {
    return "VectorMutationMessage(layerId=$layerId, operation=$operation, lonLat=${lonLat?.contentToString()}, geoJson=$geoJson, style=$style)"
  }
}
private open class MapPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VectorMutation.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VectorReply.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MapStateMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MapCameraMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VectorMutationMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VectorMutation -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VectorReply -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is MapStateMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is MapCameraMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is VectorMutationMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MapHostApi {
  suspend fun captureState(): MapStateMessage
  fun setCamera(camera: MapCameraMessage)
  fun createVectorLayer(drawOrder: Long, callback: (Result<Long>) -> Unit)
  fun mutateVectorLayer(mutation: VectorMutationMessage, callback: (Result<VectorReply>) -> Unit)
  fun pickVectorFeature(layerId: Long, x: Double, y: Double, tolerance: Double, callback: (Result<String?>) -> Unit)
  fun dispose()

  companion object {
    /** The codec used by MapHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MapPigeonCodec()
    }
    /** Sets up an instance of `MapHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MapHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapHostApi.captureState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.captureState())
              } catch (exception: Throwable) {
                MapPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapHostApi.setCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraArg = args[0] as MapCameraMessage
            val wrapped: List<Any?> = try {
              api.setCamera(cameraArg)
              listOf(null)
            } catch (exception: Throwable) {
              MapPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapHostApi.createVectorLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val drawOrderArg = args[0] as Long
            api.createVectorLayer(drawOrderArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MapPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MapPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapHostApi.mutateVectorLayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mutationArg = args[0] as VectorMutationMessage
            api.mutateVectorLayer(mutationArg) { result: Result<VectorReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MapPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MapPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapHostApi.pickVectorFeature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val layerIdArg = args[0] as Long
            val xArg = args[1] as Double
            val yArg = args[2] as Double
            val toleranceArg = args[3] as Double
            api.pickVectorFeature(layerIdArg, xArg, yArg, toleranceArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MapPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MapPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap.MapHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              MapPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
