// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FeatureError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FeatureError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FeatureError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum RoutePigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct GeoMessage: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GeoMessage? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return GeoMessage(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: GeoMessage, rhs: GeoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return RoutePigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && RoutePigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GeoMessage")
    RoutePigeonInternal.deepHash(value: latitude, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "GeoMessage(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BoundsMessage: Hashable, CustomStringConvertible {
  var south: Double
  var west: Double
  var north: Double
  var east: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BoundsMessage? {
    let south = pigeonVar_list[0] as! Double
    let west = pigeonVar_list[1] as! Double
    let north = pigeonVar_list[2] as! Double
    let east = pigeonVar_list[3] as! Double

    return BoundsMessage(
      south: south,
      west: west,
      north: north,
      east: east
    )
  }
  func toList() -> [Any?] {
    return [
      south,
      west,
      north,
      east,
    ]
  }
  static func == (lhs: BoundsMessage, rhs: BoundsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return RoutePigeonInternal.deepEquals(lhs.south, rhs.south) && RoutePigeonInternal.deepEquals(lhs.west, rhs.west) && RoutePigeonInternal.deepEquals(lhs.north, rhs.north) && RoutePigeonInternal.deepEquals(lhs.east, rhs.east)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BoundsMessage")
    RoutePigeonInternal.deepHash(value: south, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: west, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: north, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: east, hasher: &hasher)
  }

  public var description: String {
    return "BoundsMessage(south: \(String(describing: south)), west: \(String(describing: west)), north: \(String(describing: north)), east: \(String(describing: east)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RouteMessage: Hashable, CustomStringConvertible {
  var id: Int64
  var distance: Double
  var duration: Double
  var bounds: BoundsMessage
  var lonLat: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RouteMessage? {
    let id = pigeonVar_list[0] as! Int64
    let distance = pigeonVar_list[1] as! Double
    let duration = pigeonVar_list[2] as! Double
    let bounds = pigeonVar_list[3] as! BoundsMessage
    let lonLat = pigeonVar_list[4] as! FlutterStandardTypedData

    return RouteMessage(
      id: id,
      distance: distance,
      duration: duration,
      bounds: bounds,
      lonLat: lonLat
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      distance,
      duration,
      bounds,
      lonLat,
    ]
  }
  static func == (lhs: RouteMessage, rhs: RouteMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return RoutePigeonInternal.deepEquals(lhs.id, rhs.id) && RoutePigeonInternal.deepEquals(lhs.distance, rhs.distance) && RoutePigeonInternal.deepEquals(lhs.duration, rhs.duration) && RoutePigeonInternal.deepEquals(lhs.bounds, rhs.bounds) && RoutePigeonInternal.deepEquals(lhs.lonLat, rhs.lonLat)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RouteMessage")
    RoutePigeonInternal.deepHash(value: id, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: distance, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: duration, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: bounds, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: lonLat, hasher: &hasher)
  }

  public var description: String {
    return "RouteMessage(id: \(String(describing: id)), distance: \(String(describing: distance)), duration: \(String(describing: duration)), bounds: \(String(describing: bounds)), lonLat: \(String(describing: lonLat)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NavigationMessage: Hashable, CustomStringConvertible {
  var instruction: String
  var distanceToManeuver: Double
  var remainingDistance: Double
  var remainingDuration: Double
  var progress: Double
  var onRoute: Bool
  var point: GeoMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NavigationMessage? {
    let instruction = pigeonVar_list[0] as! String
    let distanceToManeuver = pigeonVar_list[1] as! Double
    let remainingDistance = pigeonVar_list[2] as! Double
    let remainingDuration = pigeonVar_list[3] as! Double
    let progress = pigeonVar_list[4] as! Double
    let onRoute = pigeonVar_list[5] as! Bool
    let point = pigeonVar_list[6] as! GeoMessage

    return NavigationMessage(
      instruction: instruction,
      distanceToManeuver: distanceToManeuver,
      remainingDistance: remainingDistance,
      remainingDuration: remainingDuration,
      progress: progress,
      onRoute: onRoute,
      point: point
    )
  }
  func toList() -> [Any?] {
    return [
      instruction,
      distanceToManeuver,
      remainingDistance,
      remainingDuration,
      progress,
      onRoute,
      point,
    ]
  }
  static func == (lhs: NavigationMessage, rhs: NavigationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return RoutePigeonInternal.deepEquals(lhs.instruction, rhs.instruction) && RoutePigeonInternal.deepEquals(lhs.distanceToManeuver, rhs.distanceToManeuver) && RoutePigeonInternal.deepEquals(lhs.remainingDistance, rhs.remainingDistance) && RoutePigeonInternal.deepEquals(lhs.remainingDuration, rhs.remainingDuration) && RoutePigeonInternal.deepEquals(lhs.progress, rhs.progress) && RoutePigeonInternal.deepEquals(lhs.onRoute, rhs.onRoute) && RoutePigeonInternal.deepEquals(lhs.point, rhs.point)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NavigationMessage")
    RoutePigeonInternal.deepHash(value: instruction, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: distanceToManeuver, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: remainingDistance, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: remainingDuration, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: progress, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: onRoute, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: point, hasher: &hasher)
  }

  public var description: String {
    return "NavigationMessage(instruction: \(String(describing: instruction)), distanceToManeuver: \(String(describing: distanceToManeuver)), remainingDistance: \(String(describing: remainingDistance)), remainingDuration: \(String(describing: remainingDuration)), progress: \(String(describing: progress)), onRoute: \(String(describing: onRoute)), point: \(String(describing: point)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RouteStepMessage: Hashable, CustomStringConvertible {
  var lonLat: FlutterStandardTypedData
  var instruction: String
  var turn: Int64
  var duration: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RouteStepMessage? {
    let lonLat = pigeonVar_list[0] as! FlutterStandardTypedData
    let instruction = pigeonVar_list[1] as! String
    let turn = pigeonVar_list[2] as! Int64
    let duration = pigeonVar_list[3] as! Double

    return RouteStepMessage(
      lonLat: lonLat,
      instruction: instruction,
      turn: turn,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      lonLat,
      instruction,
      turn,
      duration,
    ]
  }
  static func == (lhs: RouteStepMessage, rhs: RouteStepMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return RoutePigeonInternal.deepEquals(lhs.lonLat, rhs.lonLat) && RoutePigeonInternal.deepEquals(lhs.instruction, rhs.instruction) && RoutePigeonInternal.deepEquals(lhs.turn, rhs.turn) && RoutePigeonInternal.deepEquals(lhs.duration, rhs.duration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RouteStepMessage")
    RoutePigeonInternal.deepHash(value: lonLat, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: instruction, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: turn, hasher: &hasher)
    RoutePigeonInternal.deepHash(value: duration, hasher: &hasher)
  }

  public var description: String {
    return "RouteStepMessage(lonLat: \(String(describing: lonLat)), instruction: \(String(describing: instruction)), turn: \(String(describing: turn)), duration: \(String(describing: duration)))"
  }
}

private class RoutePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GeoMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return BoundsMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return RouteMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return NavigationMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return RouteStepMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RoutePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GeoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BoundsMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RouteMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? RouteStepMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RoutePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RoutePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RoutePigeonCodecWriter(data: data)
  }
}

class RoutePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RoutePigeonCodec(readerWriter: RoutePigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RouteHostApi {
  func route(requestId: Int64, start: GeoMessage, end: GeoMessage, mode: String, offline: Bool, offlineConfig: String?, completion: @escaping (Result<RouteMessage, Error>) -> Void)
  func cancelRequest(requestId: Int64) throws
  func updateNavigation(routeId: Int64, point: GeoMessage, bearing: Double) throws -> NavigationMessage
  func releaseRoute(routeId: Int64) throws
  func buildRoute(steps: [RouteStepMessage]) throws -> RouteMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RouteHostApiSetup {
  static var codec: FlutterStandardMessageCodec { RoutePigeonCodec.shared }
  /// Sets up an instance of `RouteHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RouteHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let routeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glroute.RouteHostApi.route\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      routeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let startArg = args[1] as! GeoMessage
        let endArg = args[2] as! GeoMessage
        let modeArg = args[3] as! String
        let offlineArg = args[4] as! Bool
        let offlineConfigArg: String? = nilOrValue(args[5])
        api.route(requestId: requestIdArg, start: startArg, end: endArg, mode: modeArg, offline: offlineArg, offlineConfig: offlineConfigArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      routeChannel.setMessageHandler(nil)
    }
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glroute.RouteHostApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
    let updateNavigationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glroute.RouteHostApi.updateNavigation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateNavigationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeIdArg = args[0] as! Int64
        let pointArg = args[1] as! GeoMessage
        let bearingArg = args[2] as! Double
        do {
          let result = try api.updateNavigation(routeId: routeIdArg, point: pointArg, bearing: bearingArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateNavigationChannel.setMessageHandler(nil)
    }
    let releaseRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glroute.RouteHostApi.releaseRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeIdArg = args[0] as! Int64
        do {
          try api.releaseRoute(routeId: routeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseRouteChannel.setMessageHandler(nil)
    }
    let buildRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glroute.RouteHostApi.buildRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      buildRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stepsArg = args[0] as! [RouteStepMessage]
        do {
          let result = try api.buildRoute(steps: stepsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      buildRouteChannel.setMessageHandler(nil)
    }
  }
}
