// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package software.globus.flutter.core

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object CorePigeonUtils {

  fun createConnectionError(channelName: String): FeatureError {
    return FeatureError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FeatureError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FeatureError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class GeoMessage (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GeoMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return GeoMessage(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GeoMessage
    return CorePigeonUtils.deepEquals(this.latitude, other.latitude) && CorePigeonUtils.deepEquals(this.longitude, other.longitude)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CorePigeonUtils.deepHash(this.latitude)
    result = 31 * result + CorePigeonUtils.deepHash(this.longitude)
    return result
  }
  override fun toString(): String {
    return "GeoMessage(latitude=$latitude, longitude=$longitude)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BoundsMessage (
  val south: Double,
  val west: Double,
  val north: Double,
  val east: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BoundsMessage {
      val south = pigeonVar_list[0] as Double
      val west = pigeonVar_list[1] as Double
      val north = pigeonVar_list[2] as Double
      val east = pigeonVar_list[3] as Double
      return BoundsMessage(south, west, north, east)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      south,
      west,
      north,
      east,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BoundsMessage
    return CorePigeonUtils.deepEquals(this.south, other.south) && CorePigeonUtils.deepEquals(this.west, other.west) && CorePigeonUtils.deepEquals(this.north, other.north) && CorePigeonUtils.deepEquals(this.east, other.east)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CorePigeonUtils.deepHash(this.south)
    result = 31 * result + CorePigeonUtils.deepHash(this.west)
    result = 31 * result + CorePigeonUtils.deepHash(this.north)
    result = 31 * result + CorePigeonUtils.deepHash(this.east)
    return result
  }
  override fun toString(): String {
    return "BoundsMessage(south=$south, west=$west, north=$north, east=$east)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RegionMessage (
  val id: Long,
  val name: String,
  val collection: Boolean,
  val downloadedMask: Long,
  val downloadingMask: Long,
  val size: Long,
  val localSize: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegionMessage {
      val id = pigeonVar_list[0] as Long
      val name = pigeonVar_list[1] as String
      val collection = pigeonVar_list[2] as Boolean
      val downloadedMask = pigeonVar_list[3] as Long
      val downloadingMask = pigeonVar_list[4] as Long
      val size = pigeonVar_list[5] as Long
      val localSize = pigeonVar_list[6] as Long
      return RegionMessage(id, name, collection, downloadedMask, downloadingMask, size, localSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      collection,
      downloadedMask,
      downloadingMask,
      size,
      localSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegionMessage
    return CorePigeonUtils.deepEquals(this.id, other.id) && CorePigeonUtils.deepEquals(this.name, other.name) && CorePigeonUtils.deepEquals(this.collection, other.collection) && CorePigeonUtils.deepEquals(this.downloadedMask, other.downloadedMask) && CorePigeonUtils.deepEquals(this.downloadingMask, other.downloadingMask) && CorePigeonUtils.deepEquals(this.size, other.size) && CorePigeonUtils.deepEquals(this.localSize, other.localSize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CorePigeonUtils.deepHash(this.id)
    result = 31 * result + CorePigeonUtils.deepHash(this.name)
    result = 31 * result + CorePigeonUtils.deepHash(this.collection)
    result = 31 * result + CorePigeonUtils.deepHash(this.downloadedMask)
    result = 31 * result + CorePigeonUtils.deepHash(this.downloadingMask)
    result = 31 * result + CorePigeonUtils.deepHash(this.size)
    result = 31 * result + CorePigeonUtils.deepHash(this.localSize)
    return result
  }
  override fun toString(): String {
    return "RegionMessage(id=$id, name=$name, collection=$collection, downloadedMask=$downloadedMask, downloadingMask=$downloadingMask, size=$size, localSize=$localSize)"
  }
}
private open class CorePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GeoMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BoundsMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegionMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GeoMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BoundsMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is RegionMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CoreHostApi {
  fun initialize(apiKey: String)
  fun addAssetDataSet(asset: String, dataSet: Long)
  fun regions(parent: Long?, refresh: Boolean, callback: (Result<List<RegionMessage>>) -> Unit)
  fun downloadRegion(id: Long, mask: Long)
  fun cancelRegionDownload(id: Long)
  fun deleteRegion(id: Long, mask: Long)
  fun downloadArea(requestId: Long, bounds: BoundsMessage, mask: Long, callback: (Result<Unit>) -> Unit)
  fun cancelRequest(requestId: Long)

  companion object {
    /** The codec used by CoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CorePigeonCodec()
    }
    /** Sets up an instance of `CoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.initialize(apiKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.addAssetDataSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetArg = args[0] as String
            val dataSetArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.addAssetDataSet(assetArg, dataSetArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.regions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parentArg = args[0] as Long?
            val refreshArg = args[1] as Boolean
            api.regions(parentArg, refreshArg) { result: Result<List<RegionMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CorePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.downloadRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val maskArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.downloadRegion(idArg, maskArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.cancelRegionDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRegionDownload(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.deleteRegion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val maskArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.deleteRegion(idArg, maskArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.downloadArea$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val boundsArg = args[1] as BoundsMessage
            val maskArg = args[2] as Long
            api.downloadArea(requestIdArg, boundsArg, maskArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.glmap_core.CoreHostApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRequest(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SdkEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SdkEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      CorePigeonCodec()
    }
  }
  suspend fun downloadProgress(idArg: Long, dataSetArg: Long, downloadedArg: Long, totalArg: Long, errorArg: String?, finishedArg: Boolean, areaArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.glmap_core.SdkEventsApi.downloadProgress$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(idArg, dataSetArg, downloadedArg, totalArg, errorArg, finishedArg, areaArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FeatureError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CorePigeonUtils.createConnectionError(channelName))
        }
      }
    }
  }
}
