// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class GeoMessage {
  GeoMessage({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeoMessage decode(Object result) {
    result as List<Object?>;
    return GeoMessage(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GeoMessage(latitude: $latitude, longitude: $longitude)';
  }
}

class BoundsMessage {
  BoundsMessage({
    required this.south,
    required this.west,
    required this.north,
    required this.east,
  });

  double south;

  double west;

  double north;

  double east;

  List<Object?> _toList() {
    return <Object?>[
      south,
      west,
      north,
      east,
    ];
  }

  Object encode() {
    return _toList();  }

  static BoundsMessage decode(Object result) {
    result as List<Object?>;
    return BoundsMessage(
      south: result[0]! as double,
      west: result[1]! as double,
      north: result[2]! as double,
      east: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BoundsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(south, other.south) && _deepEquals(west, other.west) && _deepEquals(north, other.north) && _deepEquals(east, other.east);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BoundsMessage(south: $south, west: $west, north: $north, east: $east)';
  }
}

class PlaceMessage {
  PlaceMessage({
    required this.name,
    required this.detail,
    required this.point,
  });

  String name;

  String detail;

  GeoMessage point;

  List<Object?> _toList() {
    return <Object?>[
      name,
      detail,
      point,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlaceMessage decode(Object result) {
    result as List<Object?>;
    return PlaceMessage(
      name: result[0]! as String,
      detail: result[1]! as String,
      point: result[2]! as GeoMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(detail, other.detail) && _deepEquals(point, other.point);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaceMessage(name: $name, detail: $detail, point: $point)';
  }
}

class RouteMessage {
  RouteMessage({
    required this.id,
    required this.distance,
    required this.duration,
    required this.bounds,
    required this.lonLat,
  });

  int id;

  double distance;

  double duration;

  BoundsMessage bounds;

  Float64List lonLat;

  List<Object?> _toList() {
    return <Object?>[
      id,
      distance,
      duration,
      bounds,
      lonLat,
    ];
  }

  Object encode() {
    return _toList();  }

  static RouteMessage decode(Object result) {
    result as List<Object?>;
    return RouteMessage(
      id: result[0]! as int,
      distance: result[1]! as double,
      duration: result[2]! as double,
      bounds: result[3]! as BoundsMessage,
      lonLat: result[4]! as Float64List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(distance, other.distance) && _deepEquals(duration, other.duration) && _deepEquals(bounds, other.bounds) && _deepEquals(lonLat, other.lonLat);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RouteMessage(id: $id, distance: $distance, duration: $duration, bounds: $bounds, lonLat: $lonLat)';
  }
}

class NavigationMessage {
  NavigationMessage({
    required this.instruction,
    required this.distanceToManeuver,
    required this.remainingDistance,
    required this.remainingDuration,
    required this.progress,
    required this.onRoute,
    required this.point,
  });

  String instruction;

  double distanceToManeuver;

  double remainingDistance;

  double remainingDuration;

  double progress;

  bool onRoute;

  GeoMessage point;

  List<Object?> _toList() {
    return <Object?>[
      instruction,
      distanceToManeuver,
      remainingDistance,
      remainingDuration,
      progress,
      onRoute,
      point,
    ];
  }

  Object encode() {
    return _toList();  }

  static NavigationMessage decode(Object result) {
    result as List<Object?>;
    return NavigationMessage(
      instruction: result[0]! as String,
      distanceToManeuver: result[1]! as double,
      remainingDistance: result[2]! as double,
      remainingDuration: result[3]! as double,
      progress: result[4]! as double,
      onRoute: result[5]! as bool,
      point: result[6]! as GeoMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(instruction, other.instruction) && _deepEquals(distanceToManeuver, other.distanceToManeuver) && _deepEquals(remainingDistance, other.remainingDistance) && _deepEquals(remainingDuration, other.remainingDuration) && _deepEquals(progress, other.progress) && _deepEquals(onRoute, other.onRoute) && _deepEquals(point, other.point);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NavigationMessage(instruction: $instruction, distanceToManeuver: $distanceToManeuver, remainingDistance: $remainingDistance, remainingDuration: $remainingDuration, progress: $progress, onRoute: $onRoute, point: $point)';
  }
}

class RegionMessage {
  RegionMessage({
    required this.id,
    required this.name,
    required this.collection,
    required this.downloadedMask,
    required this.downloadingMask,
    required this.size,
    required this.localSize,
  });

  int id;

  String name;

  bool collection;

  int downloadedMask;

  int downloadingMask;

  int size;

  int localSize;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      collection,
      downloadedMask,
      downloadingMask,
      size,
      localSize,
    ];
  }

  Object encode() {
    return _toList();  }

  static RegionMessage decode(Object result) {
    result as List<Object?>;
    return RegionMessage(
      id: result[0]! as int,
      name: result[1]! as String,
      collection: result[2]! as bool,
      downloadedMask: result[3]! as int,
      downloadingMask: result[4]! as int,
      size: result[5]! as int,
      localSize: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(collection, other.collection) && _deepEquals(downloadedMask, other.downloadedMask) && _deepEquals(downloadingMask, other.downloadingMask) && _deepEquals(size, other.size) && _deepEquals(localSize, other.localSize);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegionMessage(id: $id, name: $name, collection: $collection, downloadedMask: $downloadedMask, downloadingMask: $downloadingMask, size: $size, localSize: $localSize)';
  }
}

class RouteStepMessage {
  RouteStepMessage({
    required this.lonLat,
    required this.instruction,
    required this.turn,
    required this.duration,
  });

  Float64List lonLat;

  String instruction;

  int turn;

  double duration;

  List<Object?> _toList() {
    return <Object?>[
      lonLat,
      instruction,
      turn,
      duration,
    ];
  }

  Object encode() {
    return _toList();  }

  static RouteStepMessage decode(Object result) {
    result as List<Object?>;
    return RouteStepMessage(
      lonLat: result[0]! as Float64List,
      instruction: result[1]! as String,
      turn: result[2]! as int,
      duration: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteStepMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lonLat, other.lonLat) && _deepEquals(instruction, other.instruction) && _deepEquals(turn, other.turn) && _deepEquals(duration, other.duration);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RouteStepMessage(lonLat: $lonLat, instruction: $instruction, turn: $turn, duration: $duration)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is GeoMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is BoundsMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PlaceMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is RouteMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NavigationMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is RegionMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is RouteStepMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return GeoMessage.decode(readValue(buffer)!);
      case 130:
        return BoundsMessage.decode(readValue(buffer)!);
      case 131:
        return PlaceMessage.decode(readValue(buffer)!);
      case 132:
        return RouteMessage.decode(readValue(buffer)!);
      case 133:
        return NavigationMessage.decode(readValue(buffer)!);
      case 134:
        return RegionMessage.decode(readValue(buffer)!);
      case 135:
        return RouteStepMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SdkHostApi {
  /// Constructor for [SdkHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SdkHostApi({
      BinaryMessenger? binaryMessenger,
      String messageChannelSuffix = '',
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<void> initialize(String apiKey) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[apiKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> addAssetDataSet(String asset, int dataSet) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.addAssetDataSet$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[asset, dataSet]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<RegionMessage>> regions(int? parent, bool refresh) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.regions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[parent, refresh]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<RegionMessage>();
  }

  Future<void> downloadRegion(int id, int mask) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.downloadRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, mask]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelRegionDownload(int id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.cancelRegionDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> deleteRegion(int id, int mask) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.deleteRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, mask]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> downloadArea(int requestId, BoundsMessage bounds, int mask) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.downloadArea$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, bounds, mask]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<PlaceMessage>> search(int requestId, String text, bool offline, bool autocomplete, GeoMessage center, List<String> categories) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.search$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, text, offline, autocomplete, center, categories]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PlaceMessage>();
  }

  Future<RouteMessage> route(int requestId, GeoMessage start, GeoMessage end, String mode, bool offline, String? offlineConfig) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.route$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId, start, end, mode, offline, offlineConfig]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RouteMessage;
  }

  Future<void> cancelRequest(int requestId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.cancelRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<NavigationMessage> updateNavigation(int routeId, GeoMessage point, double bearing) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.updateNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[routeId, point, bearing]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NavigationMessage;
  }

  Future<void> releaseRoute(int routeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.releaseRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[routeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<RouteMessage> buildRoute(List<RouteStepMessage> steps) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.SdkHostApi.buildRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[steps]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RouteMessage;
  }
}

abstract class SdkEventsApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void downloadProgress(int id, int dataSet, int downloaded, int total, String? error, bool finished, bool area);

  static void setUp(SdkEventsApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.glmap_lab.SdkEventsApi.downloadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_id = args[0]! as int;
          final int arg_dataSet = args[1]! as int;
          final int arg_downloaded = args[2]! as int;
          final int arg_total = args[3]! as int;
          final String? arg_error = args[4] as String?;
          final bool arg_finished = args[5]! as bool;
          final bool arg_area = args[6]! as bool;
          try {
            api.downloadProgress(arg_id, arg_dataSet, arg_downloaded, arg_total, arg_error, arg_finished, arg_area);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

class MapFeaturesHostApi {
  /// Constructor for [MapFeaturesHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MapFeaturesHostApi({
      BinaryMessenger? binaryMessenger,
      String messageChannelSuffix = '',
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<void> setStyleOptions(Map<String, String> options, String? assetDirectory) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setStyleOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options, assetDirectory]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setTerrain(double altitudeScale, bool hillshades, bool contours, bool slopes) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setTerrain$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[altitudeScale, hillshades, contours, slopes]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setOnlineTiles(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setOnlineTiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setRasterSource(String? urlTemplate, String attribution) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setRasterSource$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[urlTemplate, attribution]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> animateCamera(GeoMessage center, double zoom, double duration, bool fly) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.animateCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[center, zoom, duration, fly]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> fitBounds(BoundsMessage bounds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.fitBounds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[bounds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setImage(int id, GeoMessage point, Uint8List png) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, point, png]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setImageGroup(int id, List<GeoMessage> points, Uint8List png) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setImageGroup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, points, png]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setMarkers(int id, String geoJson, Uint8List png, double clusteringRadius) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setMarkers$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, geoJson, png, clusteringRadius]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setBalloon(int id, GeoMessage point, String text) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setBalloon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, point, text]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setTrack(int id, Float64List lonLat, double progress, bool arrows) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, lonLat, progress, arrows]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setRouteTrack(int id, int routeId, double progress) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setRouteTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, routeId, progress]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> removeObject(int id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.removeObject$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<PlaceMessage?> pickObject(double x, double y) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.pickObject$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[x, y]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as PlaceMessage?;
  }

  Future<Float64List> project(List<GeoMessage> points) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.project$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[points]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Float64List;
  }
}

abstract class MapEventsApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void tap(GeoMessage point, double x, double y, bool longPress);

  static void setUp(MapEventsApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.glmap_lab.MapEventsApi.tap$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final GeoMessage arg_point = args[0]! as GeoMessage;
          final double arg_x = args[1]! as double;
          final double arg_y = args[2]! as double;
          final bool arg_longPress = args[3]! as bool;
          try {
            api.tap(arg_point, arg_x, arg_y, arg_longPress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
