// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum VectorMutation {
  replace,
  style,
  remove;
}

enum VectorReply {
  ready,
  superseded,
  cancelled,
  failed,
  removed;
}

class MapStateMessage {
  MapStateMessage({
    required this.latitude,
    required this.longitude,
    required this.zoom,
    required this.scale,
    required this.angle,
    required this.pitch,
    required this.originX,
    required this.originY,
  });

  double latitude;

  double longitude;

  double zoom;

  double scale;

  double angle;

  double pitch;

  double originX;

  double originY;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
      zoom,
      scale,
      angle,
      pitch,
      originX,
      originY,
    ];
  }

  Object encode() {
    return _toList();  }

  static MapStateMessage decode(Object result) {
    result as List<Object?>;
    return MapStateMessage(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
      zoom: result[2]! as double,
      scale: result[3]! as double,
      angle: result[4]! as double,
      pitch: result[5]! as double,
      originX: result[6]! as double,
      originY: result[7]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MapStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude) && _deepEquals(zoom, other.zoom) && _deepEquals(scale, other.scale) && _deepEquals(angle, other.angle) && _deepEquals(pitch, other.pitch) && _deepEquals(originX, other.originX) && _deepEquals(originY, other.originY);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MapStateMessage(latitude: $latitude, longitude: $longitude, zoom: $zoom, scale: $scale, angle: $angle, pitch: $pitch, originX: $originX, originY: $originY)';
  }
}

class MapCameraMessage {
  MapCameraMessage({
    required this.latitude,
    required this.longitude,
    required this.zoom,
    required this.angle,
    required this.pitch,
  });

  double latitude;

  double longitude;

  double zoom;

  double angle;

  double pitch;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
      zoom,
      angle,
      pitch,
    ];
  }

  Object encode() {
    return _toList();  }

  static MapCameraMessage decode(Object result) {
    result as List<Object?>;
    return MapCameraMessage(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
      zoom: result[2]! as double,
      angle: result[3]! as double,
      pitch: result[4]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MapCameraMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude) && _deepEquals(zoom, other.zoom) && _deepEquals(angle, other.angle) && _deepEquals(pitch, other.pitch);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MapCameraMessage(latitude: $latitude, longitude: $longitude, zoom: $zoom, angle: $angle, pitch: $pitch)';
  }
}

class VectorMutationMessage {
  VectorMutationMessage({
    required this.layerId,
    required this.operation,
    this.lonLat,
    this.geoJson,
    this.style,
  });

  int layerId;

  VectorMutation operation;

  Float64List? lonLat;

  String? geoJson;

  String? style;

  List<Object?> _toList() {
    return <Object?>[
      layerId,
      operation,
      lonLat,
      geoJson,
      style,
    ];
  }

  Object encode() {
    return _toList();  }

  static VectorMutationMessage decode(Object result) {
    result as List<Object?>;
    return VectorMutationMessage(
      layerId: result[0]! as int,
      operation: result[1]! as VectorMutation,
      lonLat: result[2] as Float64List?,
      geoJson: result[3] as String?,
      style: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VectorMutationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(layerId, other.layerId) && _deepEquals(operation, other.operation) && _deepEquals(lonLat, other.lonLat) && _deepEquals(geoJson, other.geoJson) && _deepEquals(style, other.style);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VectorMutationMessage(layerId: $layerId, operation: $operation, lonLat: $lonLat, geoJson: $geoJson, style: $style)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VectorMutation) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VectorReply) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is MapStateMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is MapCameraMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is VectorMutationMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VectorMutation.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : VectorReply.values[value];
      case 131:
        return MapStateMessage.decode(readValue(buffer)!);
      case 132:
        return MapCameraMessage.decode(readValue(buffer)!);
      case 133:
        return VectorMutationMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MapHostApi {
  /// Constructor for [MapHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MapHostApi({
      BinaryMessenger? binaryMessenger,
      String messageChannelSuffix = '',
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<MapStateMessage> captureState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapHostApi.captureState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MapStateMessage;
  }

  Future<void> setCamera(MapCameraMessage camera) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapHostApi.setCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[camera]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<int> createVectorLayer(int drawOrder) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapHostApi.createVectorLayer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[drawOrder]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<VectorReply> mutateVectorLayer(VectorMutationMessage mutation) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapHostApi.mutateVectorLayer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mutation]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VectorReply;
  }

  Future<String?> pickVectorFeature(int layerId, double x, double y, double tolerance) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapHostApi.pickVectorFeature$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[layerId, x, y, tolerance]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.glmap_lab.MapHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
