// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class GeoMessage {
  GeoMessage({required this.latitude, required this.longitude});

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[latitude, longitude];
  }

  Object encode() {
    return _toList();
  }

  static GeoMessage decode(Object result) {
    result as List<Object?>;
    return GeoMessage(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) &&
        _deepEquals(longitude, other.longitude);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GeoMessage(latitude: $latitude, longitude: $longitude)';
  }
}

class BoundsMessage {
  BoundsMessage({
    required this.south,
    required this.west,
    required this.north,
    required this.east,
  });

  double south;

  double west;

  double north;

  double east;

  List<Object?> _toList() {
    return <Object?>[south, west, north, east];
  }

  Object encode() {
    return _toList();
  }

  static BoundsMessage decode(Object result) {
    result as List<Object?>;
    return BoundsMessage(
      south: result[0]! as double,
      west: result[1]! as double,
      north: result[2]! as double,
      east: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BoundsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(south, other.south) &&
        _deepEquals(west, other.west) &&
        _deepEquals(north, other.north) &&
        _deepEquals(east, other.east);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BoundsMessage(south: $south, west: $west, north: $north, east: $east)';
  }
}

class RouteMessage {
  RouteMessage({
    required this.id,
    required this.distance,
    required this.duration,
    required this.bounds,
    required this.lonLat,
  });

  int id;

  double distance;

  double duration;

  BoundsMessage bounds;

  Float64List lonLat;

  List<Object?> _toList() {
    return <Object?>[id, distance, duration, bounds, lonLat];
  }

  Object encode() {
    return _toList();
  }

  static RouteMessage decode(Object result) {
    result as List<Object?>;
    return RouteMessage(
      id: result[0]! as int,
      distance: result[1]! as double,
      duration: result[2]! as double,
      bounds: result[3]! as BoundsMessage,
      lonLat: result[4]! as Float64List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(distance, other.distance) &&
        _deepEquals(duration, other.duration) &&
        _deepEquals(bounds, other.bounds) &&
        _deepEquals(lonLat, other.lonLat);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RouteMessage(id: $id, distance: $distance, duration: $duration, bounds: $bounds, lonLat: $lonLat)';
  }
}

class NavigationMessage {
  NavigationMessage({
    required this.instruction,
    required this.distanceToManeuver,
    required this.remainingDistance,
    required this.remainingDuration,
    required this.progress,
    required this.onRoute,
    required this.point,
  });

  String instruction;

  double distanceToManeuver;

  double remainingDistance;

  double remainingDuration;

  double progress;

  bool onRoute;

  GeoMessage point;

  List<Object?> _toList() {
    return <Object?>[
      instruction,
      distanceToManeuver,
      remainingDistance,
      remainingDuration,
      progress,
      onRoute,
      point,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NavigationMessage decode(Object result) {
    result as List<Object?>;
    return NavigationMessage(
      instruction: result[0]! as String,
      distanceToManeuver: result[1]! as double,
      remainingDistance: result[2]! as double,
      remainingDuration: result[3]! as double,
      progress: result[4]! as double,
      onRoute: result[5]! as bool,
      point: result[6]! as GeoMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(instruction, other.instruction) &&
        _deepEquals(distanceToManeuver, other.distanceToManeuver) &&
        _deepEquals(remainingDistance, other.remainingDistance) &&
        _deepEquals(remainingDuration, other.remainingDuration) &&
        _deepEquals(progress, other.progress) &&
        _deepEquals(onRoute, other.onRoute) &&
        _deepEquals(point, other.point);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NavigationMessage(instruction: $instruction, distanceToManeuver: $distanceToManeuver, remainingDistance: $remainingDistance, remainingDuration: $remainingDuration, progress: $progress, onRoute: $onRoute, point: $point)';
  }
}

class RouteStepMessage {
  RouteStepMessage({
    required this.lonLat,
    required this.instruction,
    required this.turn,
    required this.duration,
  });

  Float64List lonLat;

  String instruction;

  int turn;

  double duration;

  List<Object?> _toList() {
    return <Object?>[lonLat, instruction, turn, duration];
  }

  Object encode() {
    return _toList();
  }

  static RouteStepMessage decode(Object result) {
    result as List<Object?>;
    return RouteStepMessage(
      lonLat: result[0]! as Float64List,
      instruction: result[1]! as String,
      turn: result[2]! as int,
      duration: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteStepMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lonLat, other.lonLat) &&
        _deepEquals(instruction, other.instruction) &&
        _deepEquals(turn, other.turn) &&
        _deepEquals(duration, other.duration);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RouteStepMessage(lonLat: $lonLat, instruction: $instruction, turn: $turn, duration: $duration)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is GeoMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is BoundsMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is RouteMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NavigationMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is RouteStepMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return GeoMessage.decode(readValue(buffer)!);
      case 130:
        return BoundsMessage.decode(readValue(buffer)!);
      case 131:
        return RouteMessage.decode(readValue(buffer)!);
      case 132:
        return NavigationMessage.decode(readValue(buffer)!);
      case 133:
        return RouteStepMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RouteHostApi {
  /// Constructor for [RouteHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RouteHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<RouteMessage> route(
    int requestId,
    GeoMessage start,
    GeoMessage end,
    String mode,
    bool offline,
    String? offlineConfig,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glroute.RouteHostApi.route$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId, start, end, mode, offline, offlineConfig],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RouteMessage;
  }

  Future<void> cancelRequest(int requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glroute.RouteHostApi.cancelRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<NavigationMessage> updateNavigation(
    int routeId,
    GeoMessage point,
    double bearing,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glroute.RouteHostApi.updateNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[routeId, point, bearing],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NavigationMessage;
  }

  Future<void> releaseRoute(int routeId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glroute.RouteHostApi.releaseRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[routeId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<RouteMessage> buildRoute(List<RouteStepMessage> steps) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glroute.RouteHostApi.buildRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[steps],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RouteMessage;
  }
}
