// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class GeoMessage {
  GeoMessage({required this.latitude, required this.longitude});

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[latitude, longitude];
  }

  Object encode() {
    return _toList();
  }

  static GeoMessage decode(Object result) {
    result as List<Object?>;
    return GeoMessage(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) &&
        _deepEquals(longitude, other.longitude);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GeoMessage(latitude: $latitude, longitude: $longitude)';
  }
}

class BoundsMessage {
  BoundsMessage({
    required this.south,
    required this.west,
    required this.north,
    required this.east,
  });

  double south;

  double west;

  double north;

  double east;

  List<Object?> _toList() {
    return <Object?>[south, west, north, east];
  }

  Object encode() {
    return _toList();
  }

  static BoundsMessage decode(Object result) {
    result as List<Object?>;
    return BoundsMessage(
      south: result[0]! as double,
      west: result[1]! as double,
      north: result[2]! as double,
      east: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BoundsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(south, other.south) &&
        _deepEquals(west, other.west) &&
        _deepEquals(north, other.north) &&
        _deepEquals(east, other.east);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BoundsMessage(south: $south, west: $west, north: $north, east: $east)';
  }
}

class RegionMessage {
  RegionMessage({
    required this.id,
    required this.name,
    required this.collection,
    required this.downloadedMask,
    required this.downloadingMask,
    required this.size,
    required this.localSize,
  });

  int id;

  String name;

  bool collection;

  int downloadedMask;

  int downloadingMask;

  int size;

  int localSize;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      collection,
      downloadedMask,
      downloadingMask,
      size,
      localSize,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RegionMessage decode(Object result) {
    result as List<Object?>;
    return RegionMessage(
      id: result[0]! as int,
      name: result[1]! as String,
      collection: result[2]! as bool,
      downloadedMask: result[3]! as int,
      downloadingMask: result[4]! as int,
      size: result[5]! as int,
      localSize: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(name, other.name) &&
        _deepEquals(collection, other.collection) &&
        _deepEquals(downloadedMask, other.downloadedMask) &&
        _deepEquals(downloadingMask, other.downloadingMask) &&
        _deepEquals(size, other.size) &&
        _deepEquals(localSize, other.localSize);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegionMessage(id: $id, name: $name, collection: $collection, downloadedMask: $downloadedMask, downloadingMask: $downloadingMask, size: $size, localSize: $localSize)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is GeoMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is BoundsMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is RegionMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return GeoMessage.decode(readValue(buffer)!);
      case 130:
        return BoundsMessage.decode(readValue(buffer)!);
      case 131:
        return RegionMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CoreHostApi {
  /// Constructor for [CoreHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CoreHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(String apiKey) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[apiKey],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> addAssetDataSet(String asset, int dataSet) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.addAssetDataSet$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[asset, dataSet],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<RegionMessage>> regions(int? parent, bool refresh) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.regions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[parent, refresh],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<RegionMessage>();
  }

  Future<void> downloadRegion(int id, int mask) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.downloadRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id, mask],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelRegionDownload(int id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.cancelRegionDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteRegion(int id, int mask) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.deleteRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id, mask],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> downloadArea(
    int requestId,
    BoundsMessage bounds,
    int mask,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.downloadArea$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId, bounds, mask],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancelRequest(int requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.glmap_core.CoreHostApi.cancelRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class SdkEventsApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void downloadProgress(
    int id,
    int dataSet,
    int downloaded,
    int total,
    String? error,
    bool finished,
    bool area,
  );

  static void setUp(
    SdkEventsApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.glmap_core.SdkEventsApi.downloadProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_id = args[0]! as int;
          final int arg_dataSet = args[1]! as int;
          final int arg_downloaded = args[2]! as int;
          final int arg_total = args[3]! as int;
          final String? arg_error = args[4] as String?;
          final bool arg_finished = args[5]! as bool;
          final bool arg_area = args[6]! as bool;
          try {
            api.downloadProgress(
              arg_id,
              arg_dataSet,
              arg_downloaded,
              arg_total,
              arg_error,
              arg_finished,
              arg_area,
            );
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
