// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class MapApiError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "MapApiError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? MapApiError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MapPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum VectorMutation: Int, CaseIterable {
  case replace = 0
  case style = 1
  case remove = 2
}

enum VectorReply: Int, CaseIterable {
  case ready = 0
  case superseded = 1
  case cancelled = 2
  case failed = 3
  case removed = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct MapStateMessage: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double
  var zoom: Double
  var scale: Double
  var angle: Double
  var pitch: Double
  var originX: Double
  var originY: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapStateMessage? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double
    let zoom = pigeonVar_list[2] as! Double
    let scale = pigeonVar_list[3] as! Double
    let angle = pigeonVar_list[4] as! Double
    let pitch = pigeonVar_list[5] as! Double
    let originX = pigeonVar_list[6] as! Double
    let originY = pigeonVar_list[7] as! Double

    return MapStateMessage(
      latitude: latitude,
      longitude: longitude,
      zoom: zoom,
      scale: scale,
      angle: angle,
      pitch: pitch,
      originX: originX,
      originY: originY
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
      zoom,
      scale,
      angle,
      pitch,
      originX,
      originY,
    ]
  }
  static func == (lhs: MapStateMessage, rhs: MapStateMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MapPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MapPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && MapPigeonInternal.deepEquals(lhs.zoom, rhs.zoom) && MapPigeonInternal.deepEquals(lhs.scale, rhs.scale) && MapPigeonInternal.deepEquals(lhs.angle, rhs.angle) && MapPigeonInternal.deepEquals(lhs.pitch, rhs.pitch) && MapPigeonInternal.deepEquals(lhs.originX, rhs.originX) && MapPigeonInternal.deepEquals(lhs.originY, rhs.originY)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MapStateMessage")
    MapPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MapPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    MapPigeonInternal.deepHash(value: zoom, hasher: &hasher)
    MapPigeonInternal.deepHash(value: scale, hasher: &hasher)
    MapPigeonInternal.deepHash(value: angle, hasher: &hasher)
    MapPigeonInternal.deepHash(value: pitch, hasher: &hasher)
    MapPigeonInternal.deepHash(value: originX, hasher: &hasher)
    MapPigeonInternal.deepHash(value: originY, hasher: &hasher)
  }

  public var description: String {
    return "MapStateMessage(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)), zoom: \(String(describing: zoom)), scale: \(String(describing: scale)), angle: \(String(describing: angle)), pitch: \(String(describing: pitch)), originX: \(String(describing: originX)), originY: \(String(describing: originY)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MapCameraMessage: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double
  var zoom: Double
  var angle: Double
  var pitch: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MapCameraMessage? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double
    let zoom = pigeonVar_list[2] as! Double
    let angle = pigeonVar_list[3] as! Double
    let pitch = pigeonVar_list[4] as! Double

    return MapCameraMessage(
      latitude: latitude,
      longitude: longitude,
      zoom: zoom,
      angle: angle,
      pitch: pitch
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
      zoom,
      angle,
      pitch,
    ]
  }
  static func == (lhs: MapCameraMessage, rhs: MapCameraMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MapPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MapPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && MapPigeonInternal.deepEquals(lhs.zoom, rhs.zoom) && MapPigeonInternal.deepEquals(lhs.angle, rhs.angle) && MapPigeonInternal.deepEquals(lhs.pitch, rhs.pitch)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MapCameraMessage")
    MapPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MapPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    MapPigeonInternal.deepHash(value: zoom, hasher: &hasher)
    MapPigeonInternal.deepHash(value: angle, hasher: &hasher)
    MapPigeonInternal.deepHash(value: pitch, hasher: &hasher)
  }

  public var description: String {
    return "MapCameraMessage(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)), zoom: \(String(describing: zoom)), angle: \(String(describing: angle)), pitch: \(String(describing: pitch)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VectorMutationMessage: Hashable, CustomStringConvertible {
  var layerId: Int64
  var operation: VectorMutation
  var lonLat: FlutterStandardTypedData? = nil
  var geoJson: String? = nil
  var style: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VectorMutationMessage? {
    let layerId = pigeonVar_list[0] as! Int64
    let operation = pigeonVar_list[1] as! VectorMutation
    let lonLat: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])
    let geoJson: String? = nilOrValue(pigeonVar_list[3])
    let style: String? = nilOrValue(pigeonVar_list[4])

    return VectorMutationMessage(
      layerId: layerId,
      operation: operation,
      lonLat: lonLat,
      geoJson: geoJson,
      style: style
    )
  }
  func toList() -> [Any?] {
    return [
      layerId,
      operation,
      lonLat,
      geoJson,
      style,
    ]
  }
  static func == (lhs: VectorMutationMessage, rhs: VectorMutationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MapPigeonInternal.deepEquals(lhs.layerId, rhs.layerId) && MapPigeonInternal.deepEquals(lhs.operation, rhs.operation) && MapPigeonInternal.deepEquals(lhs.lonLat, rhs.lonLat) && MapPigeonInternal.deepEquals(lhs.geoJson, rhs.geoJson) && MapPigeonInternal.deepEquals(lhs.style, rhs.style)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VectorMutationMessage")
    MapPigeonInternal.deepHash(value: layerId, hasher: &hasher)
    MapPigeonInternal.deepHash(value: operation, hasher: &hasher)
    MapPigeonInternal.deepHash(value: lonLat, hasher: &hasher)
    MapPigeonInternal.deepHash(value: geoJson, hasher: &hasher)
    MapPigeonInternal.deepHash(value: style, hasher: &hasher)
  }

  public var description: String {
    return "VectorMutationMessage(layerId: \(String(describing: layerId)), operation: \(String(describing: operation)), lonLat: \(String(describing: lonLat)), geoJson: \(String(describing: geoJson)), style: \(String(describing: style)))"
  }
}

private class MapPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VectorMutation(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VectorReply(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MapStateMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return MapCameraMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return VectorMutationMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MapPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VectorMutation {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VectorReply {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MapStateMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MapCameraMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VectorMutationMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MapPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MapPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MapPigeonCodecWriter(data: data)
  }
}

class MapPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MapPigeonCodec(readerWriter: MapPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MapHostApi {
  func diagnostics() throws -> [String: Any?]
  func captureState() async throws -> MapStateMessage
  func setCamera(camera: MapCameraMessage) throws
  func createVectorLayer(drawOrder: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func mutateVectorLayer(mutation: VectorMutationMessage, completion: @escaping (Result<VectorReply, Error>) -> Void)
  func pickVectorFeature(layerId: Int64, x: Double, y: Double, tolerance: Double, completion: @escaping (Result<String?, Error>) -> Void)
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MapHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MapPigeonCodec.shared }
  /// Sets up an instance of `MapHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MapHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let diagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.diagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      diagnosticsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.diagnostics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      diagnosticsChannel.setMessageHandler(nil)
    }
    let captureStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.captureState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureStateChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.captureState()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureStateChannel.setMessageHandler(nil)
    }
    let setCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.setCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraArg = args[0] as! MapCameraMessage
        do {
          try api.setCamera(camera: cameraArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCameraChannel.setMessageHandler(nil)
    }
    let createVectorLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.createVectorLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createVectorLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let drawOrderArg = args[0] as! Int64
        api.createVectorLayer(drawOrder: drawOrderArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createVectorLayerChannel.setMessageHandler(nil)
    }
    let mutateVectorLayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.mutateVectorLayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mutateVectorLayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mutationArg = args[0] as! VectorMutationMessage
        api.mutateVectorLayer(mutation: mutationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      mutateVectorLayerChannel.setMessageHandler(nil)
    }
    let pickVectorFeatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.pickVectorFeature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickVectorFeatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let layerIdArg = args[0] as! Int64
        let xArg = args[1] as! Double
        let yArg = args[2] as! Double
        let toleranceArg = args[3] as! Double
        api.pickVectorFeature(layerId: layerIdArg, x: xArg, y: yArg, tolerance: toleranceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickVectorFeatureChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap.MapHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
