// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class FeatureError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "FeatureError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? FeatureError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FeatureError {
  return FeatureError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum FeaturesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct GeoMessage: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GeoMessage? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return GeoMessage(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: GeoMessage, rhs: GeoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && FeaturesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GeoMessage")
    FeaturesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "GeoMessage(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BoundsMessage: Hashable, CustomStringConvertible {
  var south: Double
  var west: Double
  var north: Double
  var east: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BoundsMessage? {
    let south = pigeonVar_list[0] as! Double
    let west = pigeonVar_list[1] as! Double
    let north = pigeonVar_list[2] as! Double
    let east = pigeonVar_list[3] as! Double

    return BoundsMessage(
      south: south,
      west: west,
      north: north,
      east: east
    )
  }
  func toList() -> [Any?] {
    return [
      south,
      west,
      north,
      east,
    ]
  }
  static func == (lhs: BoundsMessage, rhs: BoundsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.south, rhs.south) && FeaturesPigeonInternal.deepEquals(lhs.west, rhs.west) && FeaturesPigeonInternal.deepEquals(lhs.north, rhs.north) && FeaturesPigeonInternal.deepEquals(lhs.east, rhs.east)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BoundsMessage")
    FeaturesPigeonInternal.deepHash(value: south, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: west, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: north, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: east, hasher: &hasher)
  }

  public var description: String {
    return "BoundsMessage(south: \(String(describing: south)), west: \(String(describing: west)), north: \(String(describing: north)), east: \(String(describing: east)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlaceMessage: Hashable, CustomStringConvertible {
  var name: String
  var detail: String
  var point: GeoMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlaceMessage? {
    let name = pigeonVar_list[0] as! String
    let detail = pigeonVar_list[1] as! String
    let point = pigeonVar_list[2] as! GeoMessage

    return PlaceMessage(
      name: name,
      detail: detail,
      point: point
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      detail,
      point,
    ]
  }
  static func == (lhs: PlaceMessage, rhs: PlaceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.name, rhs.name) && FeaturesPigeonInternal.deepEquals(lhs.detail, rhs.detail) && FeaturesPigeonInternal.deepEquals(lhs.point, rhs.point)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlaceMessage")
    FeaturesPigeonInternal.deepHash(value: name, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: detail, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: point, hasher: &hasher)
  }

  public var description: String {
    return "PlaceMessage(name: \(String(describing: name)), detail: \(String(describing: detail)), point: \(String(describing: point)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RouteMessage: Hashable, CustomStringConvertible {
  var id: Int64
  var distance: Double
  var duration: Double
  var bounds: BoundsMessage
  var lonLat: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RouteMessage? {
    let id = pigeonVar_list[0] as! Int64
    let distance = pigeonVar_list[1] as! Double
    let duration = pigeonVar_list[2] as! Double
    let bounds = pigeonVar_list[3] as! BoundsMessage
    let lonLat = pigeonVar_list[4] as! FlutterStandardTypedData

    return RouteMessage(
      id: id,
      distance: distance,
      duration: duration,
      bounds: bounds,
      lonLat: lonLat
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      distance,
      duration,
      bounds,
      lonLat,
    ]
  }
  static func == (lhs: RouteMessage, rhs: RouteMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.id, rhs.id) && FeaturesPigeonInternal.deepEquals(lhs.distance, rhs.distance) && FeaturesPigeonInternal.deepEquals(lhs.duration, rhs.duration) && FeaturesPigeonInternal.deepEquals(lhs.bounds, rhs.bounds) && FeaturesPigeonInternal.deepEquals(lhs.lonLat, rhs.lonLat)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RouteMessage")
    FeaturesPigeonInternal.deepHash(value: id, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: distance, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: duration, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: bounds, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: lonLat, hasher: &hasher)
  }

  public var description: String {
    return "RouteMessage(id: \(String(describing: id)), distance: \(String(describing: distance)), duration: \(String(describing: duration)), bounds: \(String(describing: bounds)), lonLat: \(String(describing: lonLat)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NavigationMessage: Hashable, CustomStringConvertible {
  var instruction: String
  var distanceToManeuver: Double
  var remainingDistance: Double
  var remainingDuration: Double
  var progress: Double
  var onRoute: Bool
  var point: GeoMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NavigationMessage? {
    let instruction = pigeonVar_list[0] as! String
    let distanceToManeuver = pigeonVar_list[1] as! Double
    let remainingDistance = pigeonVar_list[2] as! Double
    let remainingDuration = pigeonVar_list[3] as! Double
    let progress = pigeonVar_list[4] as! Double
    let onRoute = pigeonVar_list[5] as! Bool
    let point = pigeonVar_list[6] as! GeoMessage

    return NavigationMessage(
      instruction: instruction,
      distanceToManeuver: distanceToManeuver,
      remainingDistance: remainingDistance,
      remainingDuration: remainingDuration,
      progress: progress,
      onRoute: onRoute,
      point: point
    )
  }
  func toList() -> [Any?] {
    return [
      instruction,
      distanceToManeuver,
      remainingDistance,
      remainingDuration,
      progress,
      onRoute,
      point,
    ]
  }
  static func == (lhs: NavigationMessage, rhs: NavigationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.instruction, rhs.instruction) && FeaturesPigeonInternal.deepEquals(lhs.distanceToManeuver, rhs.distanceToManeuver) && FeaturesPigeonInternal.deepEquals(lhs.remainingDistance, rhs.remainingDistance) && FeaturesPigeonInternal.deepEquals(lhs.remainingDuration, rhs.remainingDuration) && FeaturesPigeonInternal.deepEquals(lhs.progress, rhs.progress) && FeaturesPigeonInternal.deepEquals(lhs.onRoute, rhs.onRoute) && FeaturesPigeonInternal.deepEquals(lhs.point, rhs.point)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NavigationMessage")
    FeaturesPigeonInternal.deepHash(value: instruction, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: distanceToManeuver, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: remainingDistance, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: remainingDuration, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: progress, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: onRoute, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: point, hasher: &hasher)
  }

  public var description: String {
    return "NavigationMessage(instruction: \(String(describing: instruction)), distanceToManeuver: \(String(describing: distanceToManeuver)), remainingDistance: \(String(describing: remainingDistance)), remainingDuration: \(String(describing: remainingDuration)), progress: \(String(describing: progress)), onRoute: \(String(describing: onRoute)), point: \(String(describing: point)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RegionMessage: Hashable, CustomStringConvertible {
  var id: Int64
  var name: String
  var collection: Bool
  var downloadedMask: Int64
  var downloadingMask: Int64
  var size: Int64
  var localSize: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RegionMessage? {
    let id = pigeonVar_list[0] as! Int64
    let name = pigeonVar_list[1] as! String
    let collection = pigeonVar_list[2] as! Bool
    let downloadedMask = pigeonVar_list[3] as! Int64
    let downloadingMask = pigeonVar_list[4] as! Int64
    let size = pigeonVar_list[5] as! Int64
    let localSize = pigeonVar_list[6] as! Int64

    return RegionMessage(
      id: id,
      name: name,
      collection: collection,
      downloadedMask: downloadedMask,
      downloadingMask: downloadingMask,
      size: size,
      localSize: localSize
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      collection,
      downloadedMask,
      downloadingMask,
      size,
      localSize,
    ]
  }
  static func == (lhs: RegionMessage, rhs: RegionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.id, rhs.id) && FeaturesPigeonInternal.deepEquals(lhs.name, rhs.name) && FeaturesPigeonInternal.deepEquals(lhs.collection, rhs.collection) && FeaturesPigeonInternal.deepEquals(lhs.downloadedMask, rhs.downloadedMask) && FeaturesPigeonInternal.deepEquals(lhs.downloadingMask, rhs.downloadingMask) && FeaturesPigeonInternal.deepEquals(lhs.size, rhs.size) && FeaturesPigeonInternal.deepEquals(lhs.localSize, rhs.localSize)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RegionMessage")
    FeaturesPigeonInternal.deepHash(value: id, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: name, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: collection, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: downloadedMask, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: downloadingMask, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: size, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: localSize, hasher: &hasher)
  }

  public var description: String {
    return "RegionMessage(id: \(String(describing: id)), name: \(String(describing: name)), collection: \(String(describing: collection)), downloadedMask: \(String(describing: downloadedMask)), downloadingMask: \(String(describing: downloadingMask)), size: \(String(describing: size)), localSize: \(String(describing: localSize)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RouteStepMessage: Hashable, CustomStringConvertible {
  var lonLat: FlutterStandardTypedData
  var instruction: String
  var turn: Int64
  var duration: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RouteStepMessage? {
    let lonLat = pigeonVar_list[0] as! FlutterStandardTypedData
    let instruction = pigeonVar_list[1] as! String
    let turn = pigeonVar_list[2] as! Int64
    let duration = pigeonVar_list[3] as! Double

    return RouteStepMessage(
      lonLat: lonLat,
      instruction: instruction,
      turn: turn,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      lonLat,
      instruction,
      turn,
      duration,
    ]
  }
  static func == (lhs: RouteStepMessage, rhs: RouteStepMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FeaturesPigeonInternal.deepEquals(lhs.lonLat, rhs.lonLat) && FeaturesPigeonInternal.deepEquals(lhs.instruction, rhs.instruction) && FeaturesPigeonInternal.deepEquals(lhs.turn, rhs.turn) && FeaturesPigeonInternal.deepEquals(lhs.duration, rhs.duration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RouteStepMessage")
    FeaturesPigeonInternal.deepHash(value: lonLat, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: instruction, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: turn, hasher: &hasher)
    FeaturesPigeonInternal.deepHash(value: duration, hasher: &hasher)
  }

  public var description: String {
    return "RouteStepMessage(lonLat: \(String(describing: lonLat)), instruction: \(String(describing: instruction)), turn: \(String(describing: turn)), duration: \(String(describing: duration)))"
  }
}

private class FeaturesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return GeoMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return BoundsMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return PlaceMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return RouteMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return NavigationMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return RegionMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return RouteStepMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FeaturesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GeoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BoundsMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PlaceMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RouteMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? RegionMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? RouteStepMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FeaturesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FeaturesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FeaturesPigeonCodecWriter(data: data)
  }
}

class FeaturesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FeaturesPigeonCodec(readerWriter: FeaturesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SdkHostApi {
  func initialize(apiKey: String) throws
  func addAssetDataSet(asset: String, dataSet: Int64) throws
  func regions(parent: Int64?, refresh: Bool, completion: @escaping (Result<[RegionMessage], Error>) -> Void)
  func downloadRegion(id: Int64, mask: Int64) throws
  func cancelRegionDownload(id: Int64) throws
  func deleteRegion(id: Int64, mask: Int64) throws
  func downloadArea(requestId: Int64, bounds: BoundsMessage, mask: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func search(requestId: Int64, text: String, offline: Bool, autocomplete: Bool, center: GeoMessage, categories: [String], completion: @escaping (Result<[PlaceMessage], Error>) -> Void)
  func route(requestId: Int64, start: GeoMessage, end: GeoMessage, mode: String, offline: Bool, offlineConfig: String?, completion: @escaping (Result<RouteMessage, Error>) -> Void)
  func cancelRequest(requestId: Int64) throws
  func updateNavigation(routeId: Int64, point: GeoMessage, bearing: Double) throws -> NavigationMessage
  func releaseRoute(routeId: Int64) throws
  func buildRoute(steps: [RouteStepMessage]) throws -> RouteMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SdkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FeaturesPigeonCodec.shared }
  /// Sets up an instance of `SdkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SdkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        do {
          try api.initialize(apiKey: apiKeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let addAssetDataSetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.addAssetDataSet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAssetDataSetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetArg = args[0] as! String
        let dataSetArg = args[1] as! Int64
        do {
          try api.addAssetDataSet(asset: assetArg, dataSet: dataSetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addAssetDataSetChannel.setMessageHandler(nil)
    }
    let regionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.regions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      regionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parentArg: Int64? = nilOrValue(args[0])
        let refreshArg = args[1] as! Bool
        api.regions(parent: parentArg, refresh: refreshArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      regionsChannel.setMessageHandler(nil)
    }
    let downloadRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.downloadRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let maskArg = args[1] as! Int64
        do {
          try api.downloadRegion(id: idArg, mask: maskArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      downloadRegionChannel.setMessageHandler(nil)
    }
    let cancelRegionDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.cancelRegionDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRegionDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.cancelRegionDownload(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRegionDownloadChannel.setMessageHandler(nil)
    }
    let deleteRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.deleteRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let maskArg = args[1] as! Int64
        do {
          try api.deleteRegion(id: idArg, mask: maskArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteRegionChannel.setMessageHandler(nil)
    }
    let downloadAreaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.downloadArea\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadAreaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let boundsArg = args[1] as! BoundsMessage
        let maskArg = args[2] as! Int64
        api.downloadArea(requestId: requestIdArg, bounds: boundsArg, mask: maskArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadAreaChannel.setMessageHandler(nil)
    }
    let searchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.search\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let textArg = args[1] as! String
        let offlineArg = args[2] as! Bool
        let autocompleteArg = args[3] as! Bool
        let centerArg = args[4] as! GeoMessage
        let categoriesArg = args[5] as! [String]
        api.search(requestId: requestIdArg, text: textArg, offline: offlineArg, autocomplete: autocompleteArg, center: centerArg, categories: categoriesArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      searchChannel.setMessageHandler(nil)
    }
    let routeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.route\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      routeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        let startArg = args[1] as! GeoMessage
        let endArg = args[2] as! GeoMessage
        let modeArg = args[3] as! String
        let offlineArg = args[4] as! Bool
        let offlineConfigArg: String? = nilOrValue(args[5])
        api.route(requestId: requestIdArg, start: startArg, end: endArg, mode: modeArg, offline: offlineArg, offlineConfig: offlineConfigArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      routeChannel.setMessageHandler(nil)
    }
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
    let updateNavigationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.updateNavigation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateNavigationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeIdArg = args[0] as! Int64
        let pointArg = args[1] as! GeoMessage
        let bearingArg = args[2] as! Double
        do {
          let result = try api.updateNavigation(routeId: routeIdArg, point: pointArg, bearing: bearingArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateNavigationChannel.setMessageHandler(nil)
    }
    let releaseRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.releaseRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let routeIdArg = args[0] as! Int64
        do {
          try api.releaseRoute(routeId: routeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseRouteChannel.setMessageHandler(nil)
    }
    let buildRouteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.SdkHostApi.buildRoute\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      buildRouteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stepsArg = args[0] as! [RouteStepMessage]
        do {
          let result = try api.buildRoute(steps: stepsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      buildRouteChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SdkEventsApiProtocol {
  @MainActor func downloadProgress(id idArg: Int64, dataSet dataSetArg: Int64, downloaded downloadedArg: Int64, total totalArg: Int64, error errorArg: String?, finished finishedArg: Bool, area areaArg: Bool) async throws
}
class SdkEventsApi: SdkEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FeaturesPigeonCodec {
    return FeaturesPigeonCodec.shared
  }
  @MainActor func downloadProgress(id idArg: Int64, dataSet dataSetArg: Int64, downloaded downloadedArg: Int64, total totalArg: Int64, error errorArg: String?, finished finishedArg: Bool, area areaArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.glmap_lab.SdkEventsApi.downloadProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([idArg, dataSetArg, downloadedArg, totalArg, errorArg, finishedArg, areaArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FeatureError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MapFeaturesHostApi {
  func setStyleOptions(options: [String: String], assetDirectory: String?) throws
  func setTerrain(altitudeScale: Double, hillshades: Bool, contours: Bool, slopes: Bool) throws
  func setOnlineTiles(enabled: Bool) throws
  func setRasterSource(urlTemplate: String?, attribution: String) throws
  func animateCamera(center: GeoMessage, zoom: Double, duration: Double, fly: Bool) throws
  func fitBounds(bounds: BoundsMessage) throws
  func setImage(id: Int64, point: GeoMessage, png: FlutterStandardTypedData) throws
  func setImageGroup(id: Int64, points: [GeoMessage], png: FlutterStandardTypedData) throws
  func setMarkers(id: Int64, geoJson: String, png: FlutterStandardTypedData, clusteringRadius: Double) throws
  func setBalloon(id: Int64, point: GeoMessage, text: String) throws
  func setTrack(id: Int64, lonLat: FlutterStandardTypedData, progress: Double, arrows: Bool) throws
  func setRouteTrack(id: Int64, routeId: Int64, progress: Double) throws
  func removeObject(id: Int64) throws
  func pickObject(x: Double, y: Double, completion: @escaping (Result<PlaceMessage?, Error>) -> Void)
  func project(points: [GeoMessage], completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MapFeaturesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FeaturesPigeonCodec.shared }
  /// Sets up an instance of `MapFeaturesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MapFeaturesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setStyleOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setStyleOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStyleOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! [String: String]
        let assetDirectoryArg: String? = nilOrValue(args[1])
        do {
          try api.setStyleOptions(options: optionsArg, assetDirectory: assetDirectoryArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStyleOptionsChannel.setMessageHandler(nil)
    }
    let setTerrainChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setTerrain\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTerrainChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let altitudeScaleArg = args[0] as! Double
        let hillshadesArg = args[1] as! Bool
        let contoursArg = args[2] as! Bool
        let slopesArg = args[3] as! Bool
        do {
          try api.setTerrain(altitudeScale: altitudeScaleArg, hillshades: hillshadesArg, contours: contoursArg, slopes: slopesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTerrainChannel.setMessageHandler(nil)
    }
    let setOnlineTilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setOnlineTiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOnlineTilesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setOnlineTiles(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOnlineTilesChannel.setMessageHandler(nil)
    }
    let setRasterSourceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setRasterSource\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRasterSourceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlTemplateArg: String? = nilOrValue(args[0])
        let attributionArg = args[1] as! String
        do {
          try api.setRasterSource(urlTemplate: urlTemplateArg, attribution: attributionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRasterSourceChannel.setMessageHandler(nil)
    }
    let animateCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.animateCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      animateCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let centerArg = args[0] as! GeoMessage
        let zoomArg = args[1] as! Double
        let durationArg = args[2] as! Double
        let flyArg = args[3] as! Bool
        do {
          try api.animateCamera(center: centerArg, zoom: zoomArg, duration: durationArg, fly: flyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      animateCameraChannel.setMessageHandler(nil)
    }
    let fitBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.fitBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fitBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let boundsArg = args[0] as! BoundsMessage
        do {
          try api.fitBounds(bounds: boundsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fitBoundsChannel.setMessageHandler(nil)
    }
    let setImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let pointArg = args[1] as! GeoMessage
        let pngArg = args[2] as! FlutterStandardTypedData
        do {
          try api.setImage(id: idArg, point: pointArg, png: pngArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImageChannel.setMessageHandler(nil)
    }
    let setImageGroupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setImageGroup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImageGroupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let pointsArg = args[1] as! [GeoMessage]
        let pngArg = args[2] as! FlutterStandardTypedData
        do {
          try api.setImageGroup(id: idArg, points: pointsArg, png: pngArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setImageGroupChannel.setMessageHandler(nil)
    }
    let setMarkersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setMarkers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMarkersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let geoJsonArg = args[1] as! String
        let pngArg = args[2] as! FlutterStandardTypedData
        let clusteringRadiusArg = args[3] as! Double
        do {
          try api.setMarkers(id: idArg, geoJson: geoJsonArg, png: pngArg, clusteringRadius: clusteringRadiusArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMarkersChannel.setMessageHandler(nil)
    }
    let setBalloonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setBalloon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBalloonChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let pointArg = args[1] as! GeoMessage
        let textArg = args[2] as! String
        do {
          try api.setBalloon(id: idArg, point: pointArg, text: textArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBalloonChannel.setMessageHandler(nil)
    }
    let setTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let lonLatArg = args[1] as! FlutterStandardTypedData
        let progressArg = args[2] as! Double
        let arrowsArg = args[3] as! Bool
        do {
          try api.setTrack(id: idArg, lonLat: lonLatArg, progress: progressArg, arrows: arrowsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTrackChannel.setMessageHandler(nil)
    }
    let setRouteTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.setRouteTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRouteTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let routeIdArg = args[1] as! Int64
        let progressArg = args[2] as! Double
        do {
          try api.setRouteTrack(id: idArg, routeId: routeIdArg, progress: progressArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRouteTrackChannel.setMessageHandler(nil)
    }
    let removeObjectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.removeObject\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeObjectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.removeObject(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeObjectChannel.setMessageHandler(nil)
    }
    let pickObjectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.pickObject\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickObjectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let xArg = args[0] as! Double
        let yArg = args[1] as! Double
        api.pickObject(x: xArg, y: yArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickObjectChannel.setMessageHandler(nil)
    }
    let projectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.glmap_lab.MapFeaturesHostApi.project\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      projectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pointsArg = args[0] as! [GeoMessage]
        api.project(points: pointsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      projectChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MapEventsApiProtocol {
  @MainActor func tap(point pointArg: GeoMessage, x xArg: Double, y yArg: Double, longPress longPressArg: Bool) async throws
}
class MapEventsApi: MapEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FeaturesPigeonCodec {
    return FeaturesPigeonCodec.shared
  }
  @MainActor func tap(point pointArg: GeoMessage, x xArg: Double, y yArg: Double, longPress longPressArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.glmap_lab.MapEventsApi.tap\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([pointArg, xArg, yArg, longPressArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: FeatureError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
